VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsSEFLine"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public prijemnicaID As String
Public brojPrijemnice As String
Public Naziv As String
Public kolicina As Double
Public cena As Double
Public klasa As String
Public Neto As Double
Public PDV As Double
Public iznos As Double
