Attribute VB_Name = "modPoruke"
Option Explicit

Private mCache As Object

Public Function Poruka(ByVal kljuc As String) As String
    On Error GoTo EH
    If mCache Is Nothing Then BuildCache
    If mCache.Exists(kljuc) Then
        Poruka = mCache(kljuc)
    Else
        Debug.Print "modPoruke: missing key [" & kljuc & "]"
        Poruka = "[" & kljuc & "]"
    End If
    Exit Function
EH:
    Poruka = "[" & kljuc & "]"
End Function

Public Sub InvalidateCache()
    Set mCache = Nothing
End Sub

Private Sub BuildCache()
    Set mCache = CreateObject("Scripting.Dictionary")
    mCache.CompareMode = 0
    Dim ws As Worksheet
    Dim lo As ListObject
    For Each ws In ThisWorkbook.Worksheets
        For Each lo In ws.ListObjects
            If lo.Name = TBL_PORUKE Then GoTo Found
        Next lo
    Next ws
    Exit Sub
Found:
    Dim r As ListRow
    Dim k As String
    For Each r In lo.ListRows
        k = CStr(r.Range(1).Value)
        If k <> "" Then mCache(k) = CStr(r.Range(2).Value)
    Next r
End Sub

Public Sub UpsertPoruke(lo As ListObject)
    Dim existing As Object
    Set existing = CreateObject("Scripting.Dictionary")
    existing.CompareMode = 0
    Dim r As ListRow
    Dim k As String
    For Each r In lo.ListRows
        k = CStr(r.Range(1).Value)
        If k <> "" Then existing(k) = r.Index
    Next r
    UpsertRow lo, existing, "APP_MSG_GRESKA_PRI_POKRETANJU", "Gre" & ChrW(353) & "ka pri pokretanju aplikacije. Pogledajte log."
    UpsertRow lo, existing, "AGRO_LBL_MAGACIN_IZDAVANJE_ROBE", "Magacin " & ChrW(8212) & " izdavanje robe i prijem od dobavlja" & ChrW(269) & "a"
    UpsertRow lo, existing, "AGRO_LBL_IZLAZ_IZDAVANJE_ROBE", "Izlaz " & ChrW(8212) & " Izdavanje robe kooperantu"
    UpsertRow lo, existing, "AGRO_LBL_ULAZ_PRIJEM_ROBE", "Ulaz " & ChrW(8212) & " Prijem robe od dobavlja" & ChrW(269) & "a"
    UpsertRow lo, existing, "AGRO_LBL_ZAVRSI_IZDAVANJE", "Zavr" & ChrW(353) & "i izdavanje"
    UpsertRow lo, existing, "AGRO_LBL_ZAVRSI_PRIJEM", "Zavr" & ChrW(353) & "i prijem"
    UpsertRow lo, existing, "AGRO_LBL_POPUNI_PAKOVANJE_FIELD", "Popuni 'Pakovanje' field u tblArtikli pre kori" & ChrW(353) & "cenja."
    UpsertRow lo, existing, "AGRO_MSG_POKUSAVATE_DODATI", "Poku" & ChrW(353) & "avate dodati:"
    UpsertRow lo, existing, "AGRO_MSG_IZDAVANJE_ZAVRSENO", "Izdavanje zavr" & ChrW(353) & "eno:"
    UpsertRow lo, existing, "AGRO_MSG_GRESKA_PRI_CUVANJU", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju izdavanja, promene vra" & ChrW(263) & "ene:"
    UpsertRow lo, existing, "AGRO_MSG_PRIJEM_ZAVRSEN", "Prijem zavr" & ChrW(353) & "en:"
    UpsertRow lo, existing, "AGRO_MSG_POTVRDI_BESPLATAN_ULAZ", "Cena je 0. Proknjiziti besplatan/korektivni prijem (vrednost 0)?"
    UpsertRow lo, existing, "AGRO_MSG_GRESKA_PRI_CUVANJU_2", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju prijema, promene vra" & ChrW(263) & "ene:"
    UpsertRow lo, existing, "BANKA_LBL_GENERISI_CSV_COMMIT", "Generi" & ChrW(353) & "i CSV naloge"
    UpsertRow lo, existing, "BANKA_LBL_UVOZ_TRANSAKCIJA_BANKARSKIH", "Uvoz transakcija iz bankarskih izvoda " & ChrW(8212) & " mapiranje na partnere"
    UpsertRow lo, existing, "DOK_LBL_OPERATIVNI_UNOS_DOKUMENATA", "Operativni unos dokumenata, ambala" & ChrW(382) & "e i novca"
    UpsertRow lo, existing, "DOK_ERR_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju dokumenata:"
    UpsertRow lo, existing, "DOK_MSG_UNOSI_SAMO_KLASA", "Unosi se samo II klasa: obri" & ChrW(353) & "ite koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e za I klasu."
    UpsertRow lo, existing, "DOK_MSG_UNESITE_ISPRAVNU_KOLICINU", "Unesite ispravnu koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e!"
    UpsertRow lo, existing, "DOK_MSG_UNESITE_ISPRAVNU_KOLICINU_2", "Unesite ispravnu koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e za II klasu!"
    UpsertRow lo, existing, "DOK_MSG_TIP_AMBALAZE", "Tip ambala" & ChrW(382) & "e '"
    UpsertRow lo, existing, "DOK_MSG_NEMA_UNETU_TEZINU", "' nema unetu te" & ChrW(382) & "inu gajbice"
    UpsertRow lo, existing, "DOK_MSG_MATICNI_PODACI_TIP", "(Mati" & ChrW(269) & "ni podaci ? Tip ambala" & ChrW(382) & "e)."
    UpsertRow lo, existing, "DOK_MSG_BRUTO_MOZE_PRETVORITI", "Bruto se ne mo" & ChrW(382) & "e pretvoriti u neto."
    UpsertRow lo, existing, "DOK_MSG_TEZINA_AMBALAZE", "Te" & ChrW(382) & "ina ambala" & ChrW(382) & "e ("
    UpsertRow lo, existing, "DOK_MSG_JEDNAKA_BRUTO_TEZINI", "jednaka bruto te" & ChrW(382) & "ini ("
    UpsertRow lo, existing, "DOK_MSG_PROVERITE_BROJ_KOMADA", "Proverite broj komada ili tip ambala" & ChrW(382) & "e."
    UpsertRow lo, existing, "DOK_MSG_BRUTO_KLASA_MOZE", "Bruto (II klasa) se ne mo" & ChrW(382) & "e pretvoriti u neto."
    UpsertRow lo, existing, "DOK_MSG_TEZINA_AMBALAZE_KLASE", "Te" & ChrW(382) & "ina ambala" & ChrW(382) & "e II klase ("
    UpsertRow lo, existing, "DOK_MSG_GRESKA_PRI_CUVANJU", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju otpremnice. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "DOK_ERR_GRESKA", "Gre" & ChrW(353) & "ka:"
    UpsertRow lo, existing, "DOK_MSG_UNESITE_AMBALAZU_ILI", "Unesite ambala" & ChrW(382) & "u ili novac za OM ulaz."
    UpsertRow lo, existing, "DOK_MSG_IZABERITE_TIP_AMBALAZE", "Izaberite tip ambala" & ChrW(382) & "e!"
    UpsertRow lo, existing, "DOK_MSG_NEDOVOLJNO_AVANSA_RASPOLOZIVO", "Nedovoljno OM avansa! Raspolo" & ChrW(382) & "ivo:"
    UpsertRow lo, existing, "DOK_MSG_GRESKA_PRI_CUVANJU_2", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju OM ulaza. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "DOK_MSG_VALIDACIJA_NIJE_PROSLA", "Validacija nije pro" & ChrW(353) & "la. Proverite kg i ambala" & ChrW(382) & "u (razlika mora biti 0)."
    UpsertRow lo, existing, "DOK_MSG_GRESKA_PRI_CUVANJU_3", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju zbirne. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "DOK_LBL_NEISPRAVNA_KOLICINA_AMBALAZE", "Neispravna koli" & ChrW(269) & "ina ambala" & ChrW(382) & "e"
    UpsertRow lo, existing, "DOK_MSG_UNESITE_ISPRAVNU_KOLICINU_3", "Unesite ispravnu koli" & ChrW(269) & "inu vra" & ChrW(263) & "ene ambala" & ChrW(382) & "e!"
    UpsertRow lo, existing, "DOK_MSG_GRESKA_PRI_CUVANJU_4", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju prijemnice. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "DOK_MSG_UNESITE_AMBALAZU_ILI_2", "Unesite ambala" & ChrW(382) & "u ili uplatu kupca."
    UpsertRow lo, existing, "DOK_MSG_GRESKA_PRI_CUVANJU_5", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju izlaza kupca. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "DOK_ERR_GRESKA_PRI_PRIKAZU", "Gre" & ChrW(353) & "ka pri prikazu storniranih:"
    UpsertRow lo, existing, "FAK_LBL_STAMPAJ", ChrW(352) & "tampaj"
    UpsertRow lo, existing, "FAK_ERR_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju fakturisanja:"
    UpsertRow lo, existing, "FAK_ERR_GRESKA_PRI_UCITAVANJU", "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju prijemnica:"
    UpsertRow lo, existing, "FAK_MSG_ISTA_PRIJEMNICA_IZABRANA", "Ista prijemnica je izabrana vi" & ChrW(353) & "e puta:"
    UpsertRow lo, existing, "FAK_MSG_IZABRANA_PRIJEMNICA_STORNIRANA", "Izabrana prijemnica je stornirana i ne mo" & ChrW(382) & "e se fakturisati."
    UpsertRow lo, existing, "FAK_MSG_IZABRANA_PRIJEMNICA_VEC", "Izabrana prijemnica je ve" & ChrW(263) & " fakturisana i ne mo" & ChrW(382) & "e biti uklju" & ChrW(269) & "ena u novu fakturu."
    UpsertRow lo, existing, "FAK_MSG_GRESKA_PRI_KREIRANJU", "Gre" & ChrW(353) & "ka pri kreiranju fakture. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "FAK_ERR_GRESKA_PRI_IZRADI", "Gre" & ChrW(353) & "ka pri izradi fakture:"
    UpsertRow lo, existing, "FAK_MSG_NIJE_PRONADEN_FAKTURE", "Nije prona" & ChrW(273) & "en ID fakture za " & ChrW(353) & "tampu."
    UpsertRow lo, existing, "FAK_ERR_GRESKA_PRI_STAMPANJU", "Gre" & ChrW(353) & "ka pri " & ChrW(353) & "tampanju:"
    UpsertRow lo, existing, "RPT_LBL_IZVESTAJI", "Izve" & ChrW(353) & "taji"
    UpsertRow lo, existing, "RPT_LBL_PREGLED_SALDO_OTKUPLJENE", "Pregled saldo, otkupljene robe, ambala" & ChrW(382) & "e i prose" & ChrW(269) & "ne cene"
    UpsertRow lo, existing, "RPT_LBL_PRIKAZI", "Prika" & ChrW(382) & "i"
    UpsertRow lo, existing, "RPT_LBL_STAMPAJ_KARTICU", ChrW(352) & "tampaj karticu"
    UpsertRow lo, existing, "RPT_LBL_TIP_IZVESTAJA", "TIP IZVE" & ChrW(352) & "TAJA"
    UpsertRow lo, existing, "RPT_LBL_AGRO_ZADUZENJE", "Agro zadu" & ChrW(382) & "enje"
    UpsertRow lo, existing, "RPT_LBL_AMBALAZA", "Ambala" & ChrW(382) & "a"
    UpsertRow lo, existing, "RPT_LBL_KES_OTKUPAC", "Ke" & ChrW(353) & " otkupac"
    UpsertRow lo, existing, "RPT_LBL_ZADUZENJE", "Zadu" & ChrW(382) & "enje"
    UpsertRow lo, existing, "RPT_LBL_RAZDUZENJE", "Razdu" & ChrW(382) & "enje"
    UpsertRow lo, existing, "RPT_MSG_NEMA_DOSTUPNOG_IZVESTAJA", "Za izabranu kombinaciju (entitet + tip izve" & ChrW(353) & "taja) nema dostupnog izve" & ChrW(353) & "taja."
    UpsertRow lo, existing, "RPT_MSG_IZVESTAJ_NIJE_GENERISAN", "GRE" & ChrW(352) & "KA: izve" & ChrW(353) & "taj nije generisan"
    UpsertRow lo, existing, "RPT_MSG_NIJE_OSVEZENO", "NIJE OSVE" & ChrW(381) & "ENO " & ChrW(8212) & " kliknite 'Prika" & ChrW(382) & "i'"
    UpsertRow lo, existing, "RPT_MSG_PRVO_PRIKAZI", "Prvo kliknite 'Prika" & ChrW(382) & "i' da generi" & ChrW(353) & "ete izve" & ChrW(353) & "taj."
    UpsertRow lo, existing, "RPT_ERR_GENERISANJE_IZVESTAJA", "Gre" & ChrW(353) & "ka pri generisanju izve" & ChrW(353) & "taja:"
    UpsertRow lo, existing, "RPT_MSG_REVERS_VISE_NOGU", "Dokument nosi vi" & ChrW(353) & "e od jedne noge po strani za ovaj tip ambala" & ChrW(382) & "e (duplikat ili vi" & ChrW(353) & "e generacija). Koli" & ChrW(269) & "ina na reversu je verovatno naduvana."
    UpsertRow lo, existing, "RPT_MSG_NASTAVITI_STAMPU", "Nastaviti sa " & ChrW(353) & "tampom?"
    UpsertRow lo, existing, "MATICNI_ERR_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju menija " & ChrW(353) & "ifarnika:"
    UpsertRow lo, existing, "MATICNI_ERR_GRESKA_PRI_OTVARANJU_2", "Gre" & ChrW(353) & "ka pri otvaranju " & ChrW(353) & "ifarnika:"
    UpsertRow lo, existing, "OTKUP_MSG_POKUSAJ_PONOVO", ". Poku" & ChrW(353) & "aj ponovo."
    UpsertRow lo, existing, "OTKUP_MSG_UNESITE_ISPRAVNU_KOLICINU", "Unesite ispravnu koli" & ChrW(269) & "inu izdate ambala" & ChrW(382) & "e!"
    UpsertRow lo, existing, "OTKUP_MSG_IZABERITE_TIP_AMBALAZE", "Izaberite tip ambala" & ChrW(382) & "e (za II klasu)!"
    UpsertRow lo, existing, "OTKUP_MSG_IZABERITE_TIP_AMBALAZE_2", "Izaberite tip ambala" & ChrW(382) & "e (za izdatu ambala" & ChrW(382) & "u)!"
    UpsertRow lo, existing, "OTKUP_MSG_BRUTO_REZIM_UNESITE", "Bruto re" & ChrW(382) & "im: unesite broj gajbi za I klasu"
    UpsertRow lo, existing, "OTKUP_MSG_BRUTO_REZIM_UNESITE_2", "Bruto re" & ChrW(382) & "im: unesite broj gajbi za II klasu"
    UpsertRow lo, existing, "OTKUP_MSG_ZELITE_IPAK_NASTAVITE", ChrW(381) & "elite li ipak da nastavite?"
    UpsertRow lo, existing, "OTKUP_MSG_GRESKA_PRI_CUVANJU", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju otkupa. Promene su vra" & ChrW(263) & "ene."
    UpsertRow lo, existing, "OTKUP_ERR_GRESKA_PRI_UNOSU", "Gre" & ChrW(353) & "ka pri unosu otkupa:"
    UpsertRow lo, existing, "OTKUP_ERR_GRESKA_PRI_POKRETANJU", "Gre" & ChrW(353) & "ka pri pokretanju glavnog ekrana:"
    UpsertRow lo, existing, "OTKUP_LBL_GRESKA_PRI_PROVERI", "Gre" & ChrW(353) & "ka pri proveri dokumenata. Pogledajte log."
    UpsertRow lo, existing, "OTKUP_LBL_IZVESTAJ", "Izve" & ChrW(353) & "taj"
    UpsertRow lo, existing, "OTKUP_LBL_MARZA", "Mar" & ChrW(382) & "a"
    UpsertRow lo, existing, "OTKUP_LBL_IZVESTAJ_SLEDLJIVOSTI", "Izve" & ChrW(353) & "taj o sledljivosti"
    UpsertRow lo, existing, "OTKUP_LBL_GRESKA_PRI_UVOZU", "Gre" & ChrW(353) & "ka pri uvozu banke. Otvaram mapiranje za postojece stavke."
    UpsertRow lo, existing, "OTKUP_MSG_GRESKA_PRI_UVOZU", "Gre" & ChrW(353) & "ka pri uvozu bankovnih izvoda:"
    UpsertRow lo, existing, "OTKUP_LBL_SEKCIJA_IZVESTAJ_SLEDLJIVOSTI", "Sekcija: Izve" & ChrW(353) & "taj o sledljivosti"
    UpsertRow lo, existing, "OTKUP_LBL_GRESKA_PRI_SNIMANJU", "Gre" & ChrW(353) & "ka pri snimanju. Pogledajte log."
    UpsertRow lo, existing, "OTKUP_ERR_GRESKA_PRI_SNIMANJU", "Gre" & ChrW(353) & "ka pri snimanju:"
    UpsertRow lo, existing, "OTKUP_ERR_FAJL_NIJE_USPESNO", "Fajl nije uspe" & ChrW(353) & "no sa" & ChrW(269) & "uvan ili aplikacija nije zatvorena:"
    UpsertRow lo, existing, "OTKUP_ERR_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju mati" & ChrW(269) & "nih podataka:"
    UpsertRow lo, existing, "OTKUP_LBL_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju sekcije:"
    UpsertRow lo, existing, "OTKUP_ERR_GRESKA_PRI_OTVARANJU_2", "Gre" & ChrW(353) & "ka pri otvaranju sekcije '"
    UpsertRow lo, existing, "OTKUP_LBL_DANASNJI_OTKUP", "Dana" & ChrW(353) & "nji otkup"
    UpsertRow lo, existing, "OTKUP_LBL_OTPREMNICA", "otpremnica  " & ChrW(8226)
    UpsertRow lo, existing, "PAL_LBL_PREGLED_PALETA_STAMPA", "Pregled paleta, " & ChrW(353) & "tampa i prerada"
    UpsertRow lo, existing, "SEF_LBL_POSALJI_SEF", "Po" & ChrW(353) & "alji na SEF"
    UpsertRow lo, existing, "SEF_LBL_OSVEZI_STATUS", "Osve" & ChrW(382) & "i status"
    UpsertRow lo, existing, "SEF_LBL_OTKAZI_SLANJE_SEF", "Otka" & ChrW(382) & "i slanje na SEF"
    UpsertRow lo, existing, "SEF_LBL_OSVEZI_SVE_PENDING", "Osve" & ChrW(382) & "i sve Pending"
    UpsertRow lo, existing, "SEF_ERR_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju SEF forme:"
    UpsertRow lo, existing, "SEF_MSG_SEF_STATUS_OSVEZEN", "SEF status osve" & ChrW(382) & "en."
    UpsertRow lo, existing, "SEF_MSG_CANCEL_USPESNO_POSLAT", "Cancel uspe" & ChrW(353) & "no poslat."
    UpsertRow lo, existing, "SEF_MSG_STORNO_USPESNO_POSLAT", "Storno uspe" & ChrW(353) & "no poslat."
    UpsertRow lo, existing, "SEF_MSG_RECOVERY_ZAVRSEN", "Recovery zavr" & ChrW(353) & "en."
    UpsertRow lo, existing, "SEF_MSG_PENDING_FAKTURE_OSVEZENE", "Pending fakture osve" & ChrW(382) & "ene."
    UpsertRow lo, existing, "SEF_MSG_SEF_SENDING_RECOVERY", "SEF_SENDING recovery zavr" & ChrW(353) & "en."
    UpsertRow lo, existing, "SEF_MSG_SEND_POSLATA", "Faktura poslata na SEF."
    UpsertRow lo, existing, "SEF_MSG_SEND_PRIHVACENA", "Faktura poslata i prihva" & ChrW(263) & "ena na SEF-u (ACCEPTED)."
    UpsertRow lo, existing, "SEF_MSG_SEND_ODBIJENA", "SEF je ODBIO fakturu (REJECTED). Faktura NIJE prihva" & ChrW(263) & "ena " & ChrW(8212) & " proverite 'Poslednja gre" & ChrW(353) & "ka' i pripremite je za ponovno slanje."
    UpsertRow lo, existing, "SEF_MSG_SEND_TEH_GRESKA", "Tehni" & ChrW(269) & "ka gre" & ChrW(353) & "ka pri slanju na SEF (TECH_FAILED). Faktura NIJE potvr" & ChrW(273) & "ena " & ChrW(8212) & " proverite SEF portal pre ponovnog slanja."
    UpsertRow lo, existing, "SEF_MSG_SEND_NEPOZNAT_ISHOD", "Slanje je zavr" & ChrW(353) & "eno nepoznatim ishodom " & ChrW(8212) & " proverite status fakture na SEF portalu."
    UpsertRow lo, existing, "SEF_MSG_STATUS_NIJE_OSVEZEN", "SEF status NIJE osve" & ChrW(382) & "en (SEF nije vratio upotrebljiv status). Potrebna ru" & ChrW(269) & "na provera."
    UpsertRow lo, existing, "SEF_MSG_RECOVERY_NEUSPESAN", "Recovery NIJE uspeo " & ChrW(8212) & " faktura je i dalje u stanju SEF_SENDING. Proverite SEF portal."
    UpsertRow lo, existing, "SLED_LBL_POVEZI", "Pove" & ChrW(382) & "i"
    UpsertRow lo, existing, "STM_LBL_OBRISI_GEO", "Obri" & ChrW(353) & "i geo"
    UpsertRow lo, existing, "STM_LBL_CENE_PROIZVODU_SVAKA", "Cene po proizvodu " & ChrW(8212) & " svaka promena je novi red (vazi poslednji)"
    UpsertRow lo, existing, "STM_ERR_GRESKA_PRI_PROMENI", "Gre" & ChrW(353) & "ka pri promeni statusa:"
    UpsertRow lo, existing, "STM_ERR_GRESKA_PRI_UCITAVANJU", "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju liste:"
    UpsertRow lo, existing, "STM_MSG_UNESITE_KATASTARSKU_OPSTINU", "Unesite katastarsku op" & ChrW(353) & "tinu!"
    UpsertRow lo, existing, "STM_MSG_UNESITE_VALIDNU_POVRSINU", "Unesite validnu povr" & ChrW(353) & "inu!"
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_DODAVANJU", "Gre" & ChrW(353) & "ka pri dodavanju!"
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_DODAVANJU_2", "Gre" & ChrW(353) & "ka pri dodavanju cene!"
    UpsertRow lo, existing, "STM_ERR_GRESKA_PRI_DODAVANJU", "Gre" & ChrW(353) & "ka pri dodavanju:"
    UpsertRow lo, existing, "STM_MSG_NOVU_CENU_KORISTITE", "Za novu cenu koristite 'Dodaj' " & ChrW(8212) & " stari redovi ostaju radi istorije."
    UpsertRow lo, existing, "STM_ERR_GRESKA_PRI_IZMENI", "Gre" & ChrW(353) & "ka pri izmeni:"
    UpsertRow lo, existing, "STM_ERR_GRESKA_PRI_UCITAVANJU_2", "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju stanica:"
    UpsertRow lo, existing, "AGRO_MSG_GRESKA_PRI_UNOSU", "Gre" & ChrW(353) & "ka pri unosu magacina, promene vra" & ChrW(263) & "ene:"
    UpsertRow lo, existing, "BANKA_LBL_PDF_AUSWAHLEN", "Izaberi PDF"
    UpsertRow lo, existing, "GAUTH_MSG_TOKEN_AUSTAUSCH_FEHLGESCHLAGEN", "Razmena tokena nije uspela. Proveri Client ID/Secret."
    UpsertRow lo, existing, "SYNC_ERR_UVOZ_OTK_NIJE", "Uvoz OTK nije potvr" & ChrW(273) & "en zbog fatal sync gre" & ChrW(353) & "ke."
    UpsertRow lo, existing, "SYNC_ERR_GRESKE", "Gre" & ChrW(353) & "ke:"
    UpsertRow lo, existing, "SYNC_ERR_UVOZ_OTK_ZAVRSEN", "Uvoz OTK zavr" & ChrW(353) & "en sa gre" & ChrW(353) & "kama."
    UpsertRow lo, existing, "SYNC_ERR_UVOZ_OTK_ZAVRSEN_2", "Uvoz OTK zavr" & ChrW(353) & "en!"
    UpsertRow lo, existing, "SYNC_MSG_GRESKA_PRI_UVOZU", "Gre" & ChrW(353) & "ka pri uvozu OTK:"
    UpsertRow lo, existing, "SYNC_MSG_PWA_UVOZ_NIJE", "PWA uvoz OTK nije potvr" & ChrW(273) & "en. Uspe" & ChrW(353) & "ni redovi potvr" & ChrW(273) & "eni kroz row-level TX ostaju upisani, neuspe" & ChrW(353) & "ni su ozna" & ChrW(269) & "eni kao gre" & ChrW(353) & "ka. Proveri log."
    UpsertRow lo, existing, "SYNC_MSG_PWA_UVOZ_ZAVRSEN", "PWA uvoz zavr" & ChrW(353) & "en i potvr" & ChrW(273) & "en."
    UpsertRow lo, existing, "SYNC_ERR_UVOZ_ZBIRNIH_NIJE", "Uvoz zbirnih nije potvr" & ChrW(273) & "en zbog fatal sync gre" & ChrW(353) & "ke."
    UpsertRow lo, existing, "SYNC_ERR_UVOZ_ZBIRNIH_ZAVRSEN", "Uvoz zbirnih zavr" & ChrW(353) & "en sa gre" & ChrW(353) & "kama."
    UpsertRow lo, existing, "SYNC_ERR_UVOZ_ZBIRNIH_ZAVRSEN_2", "Uvoz zbirnih zavr" & ChrW(353) & "en!"
    UpsertRow lo, existing, "SYNC_MSG_GRESKA_PRI_UVOZU_2", "Gre" & ChrW(353) & "ka pri uvozu zbirnih:"
    UpsertRow lo, existing, "SYNC_MSG_UVOZ_ZBIRNIH_ZAVRSEN", "Uvoz zbirnih zavr" & ChrW(353) & "en sa gre" & ChrW(353) & "kama ili fatal sync problemom."
    UpsertRow lo, existing, "SYNC_MSG_USPESNI_REDOVI_KOJI", "Uspe" & ChrW(353) & "ni redovi koji su potvr" & ChrW(273) & "eni kroz row-level TX ostaju upisani."
    UpsertRow lo, existing, "SYNC_MSG_NEUSPESNI_REDOVI_OZNACENI", "Neuspe" & ChrW(353) & "ni redovi su ozna" & ChrW(269) & "eni kao gre" & ChrW(353) & "ka gde je writeback uspeo."
    UpsertRow lo, existing, "SYNC_MSG_UVOZ_ZBIRNIH_ZAVRSEN_2", "Uvoz zbirnih zavr" & ChrW(353) & "en i potvr" & ChrW(273) & "en."
    UpsertRow lo, existing, "OTKUP_LBL_OTKUPNI_BLOKOVI", "Otkupni blokovi  " & ChrW(187)
    UpsertRow lo, existing, "OTKUP_LBL_SAKRIJ_BLOKOVE", ChrW(171) & "  Sakrij blokove"
    UpsertRow lo, existing, "OTKUP_LBL_UKUPNO", "Ukupno kg: " & ChrW(8212)
    UpsertRow lo, existing, "OTKUP_LBL_BLOKOVIMA", "U blokovima: " & ChrW(8212)
    UpsertRow lo, existing, "OTKUP_LBL_OSTATAK", "Ostatak: " & ChrW(8212)
    UpsertRow lo, existing, "OTKUP_LBL_UKUPNO_AMB", "Ukupno amb: " & ChrW(8212)
    UpsertRow lo, existing, "OTKUP_LBL_BLOKOVIMA_AMB", "U blokovima amb: " & ChrW(8212)
    UpsertRow lo, existing, "OTKUP_LBL_OSTATAK_AMB", "Ostatak amb: " & ChrW(8212)
    UpsertRow lo, existing, "CFG_LBL_PODESAVANJA_TBLSEFCONFIG", "Pode" & ChrW(353) & "avanja (tblSEFConfig)"
    UpsertRow lo, existing, "CFG_LBL_STR", ChrW(8212)
    UpsertRow lo, existing, "CFG_LBL_STR_2", ChrW(8212)
    UpsertRow lo, existing, "CFG_ERR_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju pode" & ChrW(353) & "avanja:"
    UpsertRow lo, existing, "CFG_MSG_PRESKOCENO_GRESKA", "Preskoceno (gre" & ChrW(353) & "ka):"
    UpsertRow lo, existing, "CFG_ERR_GRESKA_PRI_CUVANJU", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju:"
    UpsertRow lo, existing, "CFG_MSG_IZLAZ_NUZDI_ALT", "(Izlaz u nu" & ChrW(382) & "di: Alt+F8 -> ShowConfigSheet.)"
    UpsertRow lo, existing, "SETUP_MSG_SETUP_USPESNO_ZAVRSEN", "Setup je uspe" & ChrW(353) & "no zavr" & ChrW(353) & "en."
    UpsertRow lo, existing, "SETUP_MSG_PODESAVANJA_MATICNI_PODACI", "Pode" & ChrW(353) & "avanja: Mati" & ChrW(269) & "ni podaci -> Pode" & ChrW(353) & "avanja (tblSEFConfig je skriven)."
    UpsertRow lo, existing, "SETUP_MSG_SETUP_ZAVRSEN_ALI", "Setup je zavr" & ChrW(353) & "en, ali postoje stavke za proveru:"
    UpsertRow lo, existing, "SETUP_ERR_GRESKA_TOKOM_SETUP", "Gre" & ChrW(353) & "ka tokom setup-a:"
    UpsertRow lo, existing, "SETUP_MSG_HEALTH_CHECK_PROSAO", "Health-check je pro" & ChrW(353) & "ao. Racunar je pode" & ChrW(353) & "en."
    UpsertRow lo, existing, "SETUP_MSG_HEALTH_CHECK_NASAO", "Health-check je na" & ChrW(353) & "ao stavke za proveru:"
    UpsertRow lo, existing, "SETUP_ERR_GRESKA_TOKOM_HEALTH", "Gre" & ChrW(353) & "ka tokom health-check-a:"
    UpsertRow lo, existing, "SETUP_MSG_APLIKACIJA_RADI_LOKALNO", "Aplikacija radi lokalno " & ChrW(8212) & " Google/PWA se ne koristi niti proverava."
    UpsertRow lo, existing, "SETUP_MSG_BANKARSKI_FOLDERI_PODESENI", "Bankarski folderi su pode" & ChrW(353) & "eni."
    UpsertRow lo, existing, "SETUP_ERR_GRESKA_PRI_PODESAVANJU", "Gre" & ChrW(353) & "ka pri pode" & ChrW(353) & "avanju bankarskih foldera:"
    UpsertRow lo, existing, "STM_ERR_GRESKA_PRI_EXPORTU", "Gre" & ChrW(353) & "ka pri exportu parcela:"
    UpsertRow lo, existing, "DOK_ERR_NEMA_AMBALAZE_NOVCA", "Nema ambala" & ChrW(382) & "e ni novca za " & ChrW(269) & "uvanje."
    UpsertRow lo, existing, "SEF_MSG_SENDING_FAKTURA_TRENUTNO", "- SENDING: Faktura se trenutno " & ChrW(353) & "alje."
    UpsertRow lo, existing, "SEF_MSG_SENT_FAKTURA_USPESNO", "- SENT: Faktura uspe" & ChrW(353) & "no primljena na SEF."
    UpsertRow lo, existing, "SEF_MSG_REJECTED_GRESKA_PROVERI", "- REJECTED: Gre" & ChrW(353) & "ka! Proveri 'Poslednja gre" & ChrW(353) & "ka'."
    UpsertRow lo, existing, "SEF_MSG_IZABERI_FAKTURU_LISTE", "Izaberi fakturu iz liste -> Klikni 'Po" & ChrW(353) & "alji na SEF'."
    UpsertRow lo, existing, "SEF_MSG_TEHNICKA_PODRSKA", "3. TEHNICKA PODR" & ChrW(352) & "KA:"
    UpsertRow lo, existing, "SEF_MSG_SVE_PROBLEME_KOJI", "Za sve probleme koji se ne re" & ChrW(353) & "avaju sa 'Osve" & ChrW(382) & "i status',"
    UpsertRow lo, existing, "SEF_MSG_KONTAKTIRAJ_ADMINISTRATORA_POSALJI", "kontaktiraj administratora i po" & ChrW(353) & "alji SEF Event Log (donja tabela)."
    UpsertRow lo, existing, "STM_MSG_PARCELA_NEMA_KATASTARSKI", "Parcela nema katastarski broj ili katastarsku op" & ChrW(353) & "tinu."
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_OTVARANJU", "Gre" & ChrW(353) & "ka pri otvaranju GeoSrbije. Pogledaj log."
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_CUVANJU", "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju geo podataka. Pogledaj log."
    UpsertRow lo, existing, "STM_MSG_KLIKNI_JOS_JEDNOM", "Klikni jo" & ChrW(353) & " jednom za brisanje geo podataka."
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_BRISANJU", "Gre" & ChrW(353) & "ka pri brisanju geo podataka. Pogledaj log."
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_UCITAVANJU", "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju koordinata. Pogledaj log."
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_OTVARANJU_2", "Gre" & ChrW(353) & "ka pri otvaranju Google Maps. Pogledaj log."
    UpsertRow lo, existing, "STM_MSG_GRESKA_PRI_OTVARANJU_3", "Gre" & ChrW(353) & "ka pri otvaranju polygon editora. Pogledaj log."
    UpsertRow lo, existing, "FAK_ERR_STORNIRANA_FAKTURA_MOZE", "Stornirana faktura se ne mo" & ChrW(382) & "e " & ChrW(353) & "tampati kao aktivna faktura:"
    UpsertRow lo, existing, "PRINT_ERR_STORNIRAN_OTKUP", "Storniran otkup se ne " & ChrW(353) & "tampa. OtkupID: "
    UpsertRow lo, existing, "PRINT_ERR_OTKUP_BLOKIRAN", ChrW(352) & "tampa otkupnog lista je zaustavljena:"
    UpsertRow lo, existing, "LIC_MSG_SERVER_NEDOSTUPAN_OFFLINE", "Server nedostupan " & ChrW(8212) & " offline grace (masina je vezana)."
    UpsertRow lo, existing, "LIC_MSG_PROPUSTAM_VEZANU_MASINU", "' " & ChrW(8212) & " propustam vezanu masinu."
    UpsertRow lo, existing, "MATICNI_MSG_PODESAVANJA", "Pode" & ChrW(353) & "avanja"
    UpsertRow lo, existing, "MONITO_ERR_NAMERNO_TESTIRANA_VBA", "Namerno testirana VBA gre" & ChrW(353) & "ka bez sensitive podataka"
    UpsertRow lo, existing, "CFG_MSG_STAMPA_OTKUPNOG_LISTA", ChrW(352) & "tampa otkupnog lista"
    UpsertRow lo, existing, "CFG_MSG_STAMPA_PALETNOG_LISTA", ChrW(352) & "tampa paletnog lista"
    UpsertRow lo, existing, "CFG_MSG_STAMPA_PRIJEMNICE_AUTO", ChrW(352) & "tampa prijemnice (auto na unos)"
    UpsertRow lo, existing, "CFG_MSG_KUPAC_UNOSI_BRUTO", "Kupac unosi BRUTO te" & ChrW(382) & "inu (oduzmi ambala" & ChrW(382) & "u)"
    UpsertRow lo, existing, "CFG_MSG_MALINA_REZIM", "Malina re" & ChrW(382) & "im"
    UpsertRow lo, existing, "CFG_MSG_PODESAVANJA_ZATVORENA", "Pode" & ChrW(353) & "avanja zatvorena."
    UpsertRow lo, existing, "CFG_MSG_PRIKAZI_CONFIG_TABELU", "Prika" & ChrW(382) & "i config tabelu"
    UpsertRow lo, existing, "SETUP_MSG_OVAJ_RACUNAR_PROSAO", "Da li je ovaj racunar pro" & ChrW(353) & "ao SetupNewPC"
    UpsertRow lo, existing, "SETUP_MSG_DATUM_VREME_ZAVRSETKA", "Datum i vreme zavr" & ChrW(353) & "etka setup-a"
    UpsertRow lo, existing, "SETUP_MSG_FOLDER_BANKARSKE_IZVODE", "Folder za bankarske izvode sa gre" & ChrW(353) & "kom"
    UpsertRow lo, existing, "SETUP_MSG_SEF_BASE_URL", "- SEF_BASE_URL nije pode" & ChrW(353) & "en."
    UpsertRow lo, existing, "SETUP_MSG_SEF_API_KEY", "- SEF_API_KEY nije pode" & ChrW(353) & "en."
    UpsertRow lo, existing, "SETUP_MSG_SEF_ENV_NIJE", "- SEF_ENV nije pode" & ChrW(353) & "en."
    UpsertRow lo, existing, "SETUP_MSG_NIJE_PODESEN", "nije pode" & ChrW(353) & "en:"
    UpsertRow lo, existing, "SETUP_MSG_FIRSTRUN_PONUDA", "Ovaj ra" & ChrW(269) & "unar jo" & ChrW(353) & " nije pode" & ChrW(353) & "en. " & ChrW(381) & "elite li da pokrenete pode" & ChrW(353) & "avanje (SetupNewPC) sada?"
    ' --- Self-update (modSelfUpdate); dijakritika preko ChrW ---
    UpsertRow lo, existing, "SU_AZURIRATI_SADA", "A" & ChrW(382) & "urirati sada? (preporu" & ChrW(269) & "eno)"
    UpsertRow lo, existing, "SU_BACKUP_NIJE", "Backup pre a" & ChrW(382) & "uriranja nije uspeo."
    UpsertRow lo, existing, "SU_PREUZIMANJE_OTKAZANO", "Preuzimanje nije uspelo (0 fajlova). A" & ChrW(382) & "uriranje otkazano."
    UpsertRow lo, existing, "SU_POKUSAJTE", "Poku" & ChrW(353) & "ajte ponovo ili preuzmite novu verziju ru" & ChrW(269) & "no."
    UpsertRow lo, existing, "SU_ZAVRSENO_FAJLOVA", "A" & ChrW(382) & "uriranje zavr" & ChrW(353) & "eno. Preuzeto fajlova: "
    UpsertRow lo, existing, "SU_ZAVRSENO_PREUZETO", "A" & ChrW(382) & "uriranje zavr" & ChrW(353) & "eno. Preuzeto: "
    UpsertRow lo, existing, "SU_GRESKA_AZURIRANJE", "Gre" & ChrW(353) & "ka pri a" & ChrW(382) & "uriranju: "
    UpsertRow lo, existing, "SU_GRESKA_2FAZA", "Gre" & ChrW(353) & "ka u 2. fazi a" & ChrW(382) & "uriranja: "
    UpsertRow lo, existing, "SU_TRUST", "Nema programskog pristupa VBA projektu." & vbCrLf & vbCrLf & "Uklju" & ChrW(269) & "i: File > Options > Trust Center > Trust Center Settings >" & vbCrLf & "Macro Settings > 'Trust access to the VBA project object model'."
    ' --- Auth / korisnici / PIN hash / audit (modAuth, modSetup, frmStammdaten, modMaticniLookups) ---
    UpsertRow lo, existing, "AUTH_MSG_SAMO_ADMIN_PRIJAVA", "Samo administrator mo" & ChrW(382) & "e da menja prijavu."
    UpsertRow lo, existing, "AUTH_MSG_SAMO_ADMIN_ISKLJUCI", "Samo administrator mo" & ChrW(382) & "e da isklju" & ChrW(269) & "i prijavu."
    UpsertRow lo, existing, "AUTH_MSG_SAMO_ADMIN_KREIRA", "Samo administrator mo" & ChrW(382) & "e da kreira korisnike."
    UpsertRow lo, existing, "AUTH_MSG_SAMO_ADMIN_PINHASH", "Samo administrator mo" & ChrW(382) & "e da menja PIN hash."
    UpsertRow lo, existing, "AUTH_MSG_SAMO_ADMIN_KORISNICI", "Samo administrator mo" & ChrW(382) & "e da upravlja korisnicima."
    UpsertRow lo, existing, "AUTH_MSG_SAMO_ADMIN_SEKCIJA", "Ovoj sekciji pristupa samo administrator."
    UpsertRow lo, existing, "AUTH_MSG_NEMA_ADMINA", "Ne mogu da uklju" & ChrW(269) & "im prijavu: ne postoji nijedan aktivan Admin." & vbCrLf & "Prvo pokreni: Alt+F8 -> KreirajPrvogAdmina."
    UpsertRow lo, existing, "AUTH_ERR_NE_MOGU_UKLJUCITI", "Ne mogu da uklju" & ChrW(269) & "im prijavu: "
    UpsertRow lo, existing, "AUTH_MSG_PRIJAVA_UKLJUCENA", "Prijava korisnika je UKLJU" & ChrW(268) & "ENA." & vbCrLf & "Pri slede" & ChrW(263) & "em otvaranju aplikacije tra" & ChrW(382) & "i se prijava."
    UpsertRow lo, existing, "AUTH_MSG_PRIJAVA_ISKLJUCENA", "Prijava korisnika je ISKLJU" & ChrW(268) & "ENA (app radi bez prijave)."
    UpsertRow lo, existing, "AUTH_MSG_VEC_POSTOJI", "' ve" & ChrW(263) & " postoji."
    UpsertRow lo, existing, "AUTH_MSG_ADMIN_KREIRAN", "' je kreiran." & vbCrLf & vbCrLf & "Slede" & ChrW(263) & "e: uklju" & ChrW(269) & "i prijavu sa Alt+F8 -> EnableAuth."
    UpsertRow lo, existing, "AUTH_ERR_SHA_NE_RADI", "SHA-256 ne radi u ovom okru" & ChrW(382) & "enju (pokreni Alt+F8 -> TestPinHash)." & vbCrLf & "PIN hash NIJE uklju" & ChrW(269) & "en."
    UpsertRow lo, existing, "AUTH_MSG_PINHASH_UKLJUCEN", "PIN hash je UKLJU" & ChrW(268) & "EN." & vbCrLf & "Postoje" & ChrW(263) & "i plaintext PIN-ovi migriraju na hash pri prvoj prijavi;" & vbCrLf & "novi/izmenjeni PIN-ovi se odmah " & ChrW(269) & "uvaju kao hash."
    UpsertRow lo, existing, "AUTH_MSG_PINHASH_ISKLJUCEN", "PIN hash je ISKLJU" & ChrW(268) & "EN (novi PIN-ovi se " & ChrW(269) & "uvaju kao plaintext)."
    UpsertRow lo, existing, "AUTH_MSG_PRIJAVA_NEUSPESNA", "Prijava neuspe" & ChrW(353) & "na. Aplikacija se zatvara."
    UpsertRow lo, existing, "AUTH_LBL_PRIJAVA_GRESKA", "Pogre" & ChrW(353) & "no korisni" & ChrW(269) & "ko ime ili PIN."
    UpsertRow lo, existing, "AUTH_MSG_PINHASH_RADI", "PIN hash (SHA-256) RADI ispravno u ovom okru" & ChrW(382) & "enju." & vbCrLf & "Mo" & ChrW(382) & "e" & ChrW(353) & " uklju" & ChrW(269) & "iti: Alt+F8 -> EnablePinHash."
    UpsertRow lo, existing, "AUTH_MSG_PINHASH_NE_RADI", "PIN hash NE radi u ovom okru" & ChrW(382) & "enju (SHA-256 nedostupan)." & vbCrLf & "NE uklju" & ChrW(269) & "uj PIN hash " & ChrW(8212) & " ostani na plaintext PIN-u." & vbCrLf & "Dobijeno: '"
    UpsertRow lo, existing, "AUD_MSG_KOLONE_SUFIX", " tabela:" & vbCrLf & "CreatedAt / CreatedBy / ModifiedAt / ModifiedBy." & vbCrLf & vbCrLf & "Od sada se svaki unos i izmena bele" & ChrW(382) & "e (ko i kada)."
    UpsertRow lo, existing, "GEN_ERR_GRESKA", "Gre" & ChrW(353) & "ka: "
    UpsertRow lo, existing, "KOR_LBL_KORISNICKO_IME", "Korisni" & ChrW(269) & "ko ime"
    UpsertRow lo, existing, "KOR_MSG_UNESITE_IME", "Unesite korisni" & ChrW(269) & "ko ime!"
    UpsertRow lo, existing, "KOR_MSG_VEC_POSTOJI", "' ve" & ChrW(263) & " postoji!"
    ' ===== OTKUI_* : ekran "Otkup i prodaja" v5 (modOtkupUI / frmOtkupUI / clsFlatBtn) =====
    UpsertRow lo, existing, "OTKUI_APP_CAPTION", "AgriX OtkupApp - Otkup i prodaja"
    UpsertRow lo, existing, "OTKUI_HDR_STATUS", "Online  " & ChrW(183) & "  Dusan  " & ChrW(183) & "  Sezona 2026"
    UpsertRow lo, existing, "OTKUI_HDR_SACUVANO", "Sve izmene sa" & ChrW(269) & "uvane"
    UpsertRow lo, existing, "OTKUI_HDR_NESACUVANO", "Nesa" & ChrW(269) & "uvan unos"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_OTKUP", "Sa" & ChrW(269) & "uvaj otkupni list"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_OTPREMNICA", "Sa" & ChrW(269) & "uvaj otpremnicu"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_ZBIRNA", "Sa" & ChrW(269) & "uvaj zbirnu"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_PRIJEMNICA", "Sa" & ChrW(269) & "uvaj prijemnicu"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_AMB_ISPLATE", "Sa" & ChrW(269) & "uvaj isplatu"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_AMB_UPLATE", "Sa" & ChrW(269) & "uvaj uplatu"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_REVERSI", "Sa" & ChrW(269) & "uvaj revers"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_STORNO", "Storniraj dokument"
    UpsertRow lo, existing, "OTKUI_BTN_MATICNI", "Mati" & ChrW(269) & "ni podaci"

    ' --- alatke aplikacije (zaglavlje + desna kolona) --------------------
    UpsertRow lo, existing, "OTKUI_BTN_SYNC", "Sinhronizuj"
    UpsertRow lo, existing, "OTKUI_BTN_SNIMI", "Snimi radnu svesku"
    UpsertRow lo, existing, "OTKUI_BTN_EXCEL", "Otvori Excel"
    UpsertRow lo, existing, "OTKUI_OPERATER_NEPOZNAT", "Operater"
    UpsertRow lo, existing, "OTKUI_SYNC_OK", "Sinhronizovano"
    UpsertRow lo, existing, "OTKUI_SYNC_PAO", "Sinhronizacija nije uspela"
    UpsertRow lo, existing, "OTKUI_MSG_SYNC_START", "Sinhronizacija u toku" & ChrW(8230)
    UpsertRow lo, existing, "OTKUI_MSG_SYNC_OK", "Sinhronizacija zavr" & ChrW(353) & "ena."
    UpsertRow lo, existing, "OTKUI_MSG_SYNC_PAO", "Sinhronizacija nije uspela " & ChrW(8212) & " vidi Immediate/log."
    UpsertRow lo, existing, "OTKUI_MSG_WB_SNIMLJENA", "Radna sveska je snimljena."
    UpsertRow lo, existing, "OTKUI_MSG_WB_PALO", "Snimanje radne sveske nije uspelo."
    UpsertRow lo, existing, "OTKUI_MSG_AUTH_OFF", "Prijava korisnika nije uklju" & ChrW(269) & "ena (AUTH)."
    UpsertRow lo, existing, "OTKUI_MSG_OPERATER", "Operater je sada"
    UpsertRow lo, existing, "OTKUI_MSG_OPERATER_ISTI", "Operater nije promenjen, ostaje"
    UpsertRow lo, existing, "OTKUI_MSG_OPERATER_PAO", "Zamena operatera nije uspela."

    UpsertRow lo, existing, "OTKUI_NAVG_OPERACIJE", "OPERACIJE"
    UpsertRow lo, existing, "OTKUI_NAVG_FINANSIJE", "FINANSIJE"
    UpsertRow lo, existing, "OTKUI_NAVG_ANALITIKA", "ANALITIKA"
    UpsertRow lo, existing, "OTKUI_NAV_OTKUP", "Otkup i prodaja"
    UpsertRow lo, existing, "OTKUI_NAV_BLOKOVI", "Otkupni blokovi"
    UpsertRow lo, existing, "OTKUI_NAV_UNOS", "Unos dokumenata"
    UpsertRow lo, existing, "OTKUI_NAV_PALETE", "Palete"
    UpsertRow lo, existing, "OTKUI_NAV_AGRO", "Agrohemija"
    UpsertRow lo, existing, "OTKUI_NAV_FAKT", "Fakturisanje"
    UpsertRow lo, existing, "OTKUI_NAV_BANKA_UVOZ", "Uvoz izvoda"
    UpsertRow lo, existing, "OTKUI_NAV_BANKA_NALOZI", "Platni nalozi"
    UpsertRow lo, existing, "OTKUI_NAV_MARZA", "Mar" & ChrW(382) & "a"
    UpsertRow lo, existing, "OTKUI_NAV_IZVESTAJI", "Izve" & ChrW(353) & "taji"
    UpsertRow lo, existing, "OTKUI_NAV_SLEDLJIVOST", "Sledljivost"
    UpsertRow lo, existing, "OTKUI_FOOT_SEZONA", "Sezona 2026"

    UpsertRow lo, existing, "OTKUI_KPI_DANAS", "DANAS OTKUPLJENO"
    UpsertRow lo, existing, "OTKUI_KPI_OM_SALDO", "OM SALDO"
    UpsertRow lo, existing, "OTKUI_KPI_OTVORENO", "OTVORENO KG"
    UpsertRow lo, existing, "OTKUI_KPI_DOKUMENATA", "DOKUMENATA"
    UpsertRow lo, existing, "OTKUI_KPI_VALIDACIJA", "VALIDACIJA"
    UpsertRow lo, existing, "OTKUI_KPI_SPREMNO", "Spremno za unos"

    ' --- 8 dokumenata: F1..F8 -------------------------------------------
    ' TITLE = pun naziv (veliki naslov, ima celu sirinu zone)
    ' MODE  = KRATKO ime za karticu u desnoj koloni (108pt, ~25 znakova)
    ' Stari kljucevi (IZLAZ_OM / ULAZ_OM / ULAZ_KUPCI / IZLAZ_KUPCI) su
    ' zamenjeni imenima dokumenata; UpsertPoruke ne brise redove, pa stari
    ' ostaju u tabeli neupotrebljeni - to je bezopasno.
    UpsertRow lo, existing, "OTKUI_TITLE_OTKUP", "Otkupni list"
    UpsertRow lo, existing, "OTKUI_TITLE_OTPREMNICA", "Otpremnica"
    UpsertRow lo, existing, "OTKUI_TITLE_ZBIRNA", "Zbirna otpremnica"
    UpsertRow lo, existing, "OTKUI_TITLE_PRIJEMNICA", "Prijemnice"
    ' NE "Gotovinske": rezim namerno prikazuje OBA kanala - i blagajnu i novac
    ' uvezen iz bankovnih izvoda. Kanal se vidi u 4. koloni mreze.
    UpsertRow lo, existing, "OTKUI_TITLE_AMB_ISPLATE", "Isplate"
    UpsertRow lo, existing, "OTKUI_TITLE_AMB_UPLATE", "Kupci - uplate"
    UpsertRow lo, existing, "OTKUI_TITLE_STORNO", "Storno"
    UpsertRow lo, existing, "OTKUI_TITLE_REVERSI", "Ambala" & ChrW(382) & "a " & ChrW(8212) & " kretanje kod kooperanta i OM"

    UpsertRow lo, existing, "OTKUI_SUB_OTKUP", "Otkup robe od kooperanta na otkupnom mestu"
    UpsertRow lo, existing, "OTKUI_SUB_OTPREMNICA", "Evidencija izlaza robe iz otkupnog mesta"
    UpsertRow lo, existing, "OTKUI_SUB_ZBIRNA", "Objedinjavanje prijemnica u jednu zbirnu"
    UpsertRow lo, existing, "OTKUI_SUB_PRIJEMNICA", "Prijem robe od kupca"
    UpsertRow lo, existing, "OTKUI_SUB_AMB_ISPLATE", "Isplate kooperantu i otkupnom mestu " & ChrW(8212) & " gotovina i bankovni izvodi"
    UpsertRow lo, existing, "OTKUI_SUB_AMB_UPLATE", "Uplate od kupca " & ChrW(8212) & " gotovina i bankovni izvodi"
    UpsertRow lo, existing, "OTKUI_SUB_REVERSI", "Reversi i predaja punih gajbi " & ChrW(8212) & " po jedan red za svaki dokument"
    UpsertRow lo, existing, "OTKUI_SUB_STORNO", "Poni" & ChrW(353) & "tavanje pogre" & ChrW(353) & "no unetih dokumenata"

    UpsertRow lo, existing, "OTKUI_MODE_OTKUP", "Otkupni list"
    UpsertRow lo, existing, "OTKUI_MODE_OTPREMNICA", "Otpremnica"
    UpsertRow lo, existing, "OTKUI_MODE_ZBIRNA", "Zbirna otpremnica"
    UpsertRow lo, existing, "OTKUI_MODE_PRIJEMNICA", "Prijemnice"
    UpsertRow lo, existing, "OTKUI_MODE_AMB_ISPLATE", "Isplate"
    UpsertRow lo, existing, "OTKUI_MODE_AMB_UPLATE", "Kupci - uplate"
    UpsertRow lo, existing, "OTKUI_MODE_STORNO", "Storno"
    UpsertRow lo, existing, "OTKUI_MODE_REVERSI", "Reversi ambala" & ChrW(382) & "e"

    UpsertRow lo, existing, "OTKUI_HINT_OTKUP", "otkupi od kooperanata"
    UpsertRow lo, existing, "OTKUI_HINT_OTPREMNICA", "izlazi sa otkupnog mesta"
    UpsertRow lo, existing, "OTKUI_HINT_ZBIRNA", "prijemnice " & ChrW(269) & "ekaju novu zbirnu"
    UpsertRow lo, existing, "OTKUI_HINT_PRIJEMNICA", "ulazi kupaca danas"
    UpsertRow lo, existing, "OTKUI_HINT_AMB_ISPLATE", "gotovina i izvodi, ka kooperantu i OM"
    UpsertRow lo, existing, "OTKUI_HINT_AMB_UPLATE", "gotovina i izvodi, od kupca"
    UpsertRow lo, existing, "OTKUI_HINT_REVERSI", "izdato i vra" & ChrW(263) & "eno, u komadima"
    UpsertRow lo, existing, "OTKUI_HINT_STORNO", "poni" & ChrW(353) & "teni dokumenti"

    UpsertRow lo, existing, "OTKUI_GRID_TITLE_OTKUP", "Postoje" & ChrW(263) & "i otkupni listovi"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_OTPREMNICA", "Postoje" & ChrW(263) & "e otpremnice"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_ZBIRNA", "Postoje" & ChrW(263) & "e zbirne"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_PRIJEMNICA", "Postoje" & ChrW(263) & "e prijemnice"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_AMB_ISPLATE", "Postoje" & ChrW(263) & "e isplate"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_AMB_UPLATE", "Postoje" & ChrW(263) & "e uplate"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_REVERSI", "Kretanje ambala" & ChrW(382) & "e"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_STORNO", "Stornirani dokumenti"

    UpsertRow lo, existing, "OTKUI_FLDBROJ_OTKUP", "BROJ OTKUPNOG LISTA"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_OTPREMNICA", "BROJ OTPREMNICE"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_ZBIRNA", "BROJ ZBIRNE"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_PRIJEMNICA", "BROJ PRIJEMNICE"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_AMB_ISPLATE", "BROJ DOKUMENTA"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_AMB_UPLATE", "BROJ DOKUMENTA"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_REVERSI", "BROJ REVERSA"
    UpsertRow lo, existing, "OTKUI_FLDBROJ_STORNO", "BROJ DOKUMENTA"

    ' natpis polja PARTNER - onaj koga zaduzujemo ili razduzujemo

    ' 4. kolona mreze: KG za robu, KANAL za gotovinski promet, TIP AMB. za reverse
    UpsertRow lo, existing, "OTKUI_HD_KANAL", "KANAL"
    UpsertRow lo, existing, "OTKUI_MSG_MREZA_PALA", "U" & ChrW(269) & "itavanje mre" & ChrW(382) & "e nije uspelo na koraku:"
    UpsertRow lo, existing, "OTKUI_MSG_ZBIRNA_AKTIVNA", "Aktivna zbirna:"
    UpsertRow lo, existing, "OTKUI_HD_OSNOV", "OSNOV"
    UpsertRow lo, existing, "OTKUI_OSN_REV_IZDATO", "Revers " & ChrW(8212) & " izdato"
    UpsertRow lo, existing, "OTKUI_OSN_REV_POVRAT", "Revers " & ChrW(8212) & " povrat"
    UpsertRow lo, existing, "OTKUI_OSN_REV_OM_IZDATO", "Revers " & ChrW(8212) & " OM izdato"
    UpsertRow lo, existing, "OTKUI_OSN_REV_OM_PRIJEM", "Revers " & ChrW(8212) & " OM prijem"
    UpsertRow lo, existing, "OTKUI_OSN_OTKUP_PUNE", "Uz otkup " & ChrW(8212) & " pune"
    UpsertRow lo, existing, "OTKUI_OSN_OTKUP_PRAZNE", "Uz otkup " & ChrW(8212) & " prazne"
    UpsertRow lo, existing, "OTKUI_HD_SMER", "SMER"
    UpsertRow lo, existing, "OTKUI_HD_PLACENO", "PLA" & ChrW(262) & "ENO"
    UpsertRow lo, existing, "OTKUI_HD_OSTATAK", "OSTATAK"
    UpsertRow lo, existing, "OTKUI_PAY_PLACENO", "Pla" & ChrW(263) & "eno"
    UpsertRow lo, existing, "OTKUI_PAY_DELIMICNO", "Delimi" & ChrW(269) & "no"
    UpsertRow lo, existing, "OTKUI_PAY_NEPLACENO", "Nepla" & ChrW(263) & "eno"
    UpsertRow lo, existing, "OTKUI_PAY_NEFAKT", "Nefakturisano"
    UpsertRow lo, existing, "OTKUI_HD_VRSTA", "VRSTA"
    UpsertRow lo, existing, "OTKUI_HD_SORTA", "SORTA"
    UpsertRow lo, existing, "OTKUI_HD_KLASA", "KLASA"
    UpsertRow lo, existing, "OTKUI_HD_KOL_AMB", "KOL. AMB."
    UpsertRow lo, existing, "OTKUI_HD_TIP_AMB", "TIP AMBALA" & ChrW(381) & "E"
    UpsertRow lo, existing, "OTKUI_HD_KOMADA", "KOMADA"
    UpsertRow lo, existing, "OTKUI_UNIT_KOM", "kom"
    UpsertRow lo, existing, "OTKUI_KANAL_KES", "Gotovina"
    UpsertRow lo, existing, "OTKUI_KANAL_BANKA", "Banka"

    UpsertRow lo, existing, "OTKUI_LBL_KONTEKST", "KONTEKST"
    UpsertRow lo, existing, "OTKUI_LBL_OSNOVNI", "OSNOVNI PODACI"
    UpsertRow lo, existing, "OTKUI_CTXL_VRSTA", "Vrsta"
    UpsertRow lo, existing, "OTKUI_CTXL_SORTA", "Sorta"
    UpsertRow lo, existing, "OTKUI_CTXL_OM", "Otkupno mesto"
    UpsertRow lo, existing, "OTKUI_CTXL_VOZAC", "Voza" & ChrW(269)
    UpsertRow lo, existing, "OTKUI_CTXL_PARTNER", "Partner"
    UpsertRow lo, existing, "OTKUI_FLDPART_OTKUP", "Kooperant"
    UpsertRow lo, existing, "OTKUI_FLDPART_OTPREMNICA", "Kupac"
    UpsertRow lo, existing, "OTKUI_FLDPART_ZBIRNA", "Kupac"
    UpsertRow lo, existing, "OTKUI_FLDPART_PRIJEMNICA", "Kupac"
    UpsertRow lo, existing, "OTKUI_FLDPART_AMB_UPLATE", "Kupac"
    UpsertRow lo, existing, "OTKUI_FLDPART_AMB_ISPLATE", "Primalac"
    UpsertRow lo, existing, "OTKUI_FLDPART_STORNO", "Partner"
    UpsertRow lo, existing, "OTKUI_FLDPART_REVERSI", "Partner"
    UpsertRow lo, existing, "OTKUI_PTIP_KOOP", "kooperant"
    UpsertRow lo, existing, "OTKUI_PTIP_OM", "otkupno mesto"
    UpsertRow lo, existing, "OTKUI_PTIP_KUP", "kupac"
    UpsertRow lo, existing, "OTKUI_FLD_NOVAC", "NOVAC"
    UpsertRow lo, existing, "OTKUI_FLD_SMER_REV", "SMER REVERSA"
    UpsertRow lo, existing, "OTKUI_SEG_REV_IZD_KOOP", "Izdato koop."
    UpsertRow lo, existing, "OTKUI_SEG_REV_PRI_KOOP", "Prijem koop."
    UpsertRow lo, existing, "OTKUI_SEG_REV_IZD_OM", "Izdato OM"
    UpsertRow lo, existing, "OTKUI_SEG_REV_PRI_OM", "Prijem od OM"
    UpsertRow lo, existing, "OTKUI_CTX_VRSTA", "Jabuka"
    UpsertRow lo, existing, "OTKUI_CTX_SORTA", "Idared"
    UpsertRow lo, existing, "OTKUI_CTX_OM", "OM Zaovine"
    UpsertRow lo, existing, "OTKUI_CTX_VOZAC", "M. Peri" & ChrW(263)

    UpsertRow lo, existing, "OTKUI_FLD_BROJ_OTPR", "BROJ OTPREMNICE"
    UpsertRow lo, existing, "OTKUI_FLD_BROJ_ZBIRNE", "BROJ ZBIRNE"
    UpsertRow lo, existing, "OTKUI_FLD_DATUM", "DATUM"
    UpsertRow lo, existing, "OTKUI_FLD_KOL_AMB_II", "GAJBE II KLASE"
    UpsertRow lo, existing, "OTKUI_FLD_TIP_AMB", "TIP AMBALA" & ChrW(381) & "E"
    UpsertRow lo, existing, "OTKUI_FLD_KG_I", "KOLI" & ChrW(268) & "INA I KLASA"
    UpsertRow lo, existing, "OTKUI_FLD_KG_II", "KOLI" & ChrW(268) & "INA II KLASA"
    UpsertRow lo, existing, "OTKUI_FLD_CENA", "CENA"
    UpsertRow lo, existing, "OTKUI_FLD_KLASA_CENA", "Klasa i cena RSD/kg"
    UpsertRow lo, existing, "OTKUI_GRP_DOK", "Dokument"
    UpsertRow lo, existing, "OTKUI_GRP_ROBA", "Roba i cena"
    UpsertRow lo, existing, "OTKUI_GRP_AMB", "Ambala" & ChrW(382) & "a"
    UpsertRow lo, existing, "OTKUI_GRP_NOV", "Novac"
    UpsertRow lo, existing, "OTKUI_FLD_AMB_PR_OTKUP", "Izdata ambala" & ChrW(382) & "a"
    UpsertRow lo, existing, "OTKUI_FLD_AMB_PR_PRIJEMNICA", "Povrat ambala" & ChrW(382) & "e"
    UpsertRow lo, existing, "OTKUI_TIP_AMB_EQ", "Prepi" & ChrW(353) & "i koli" & ChrW(269) & "inu predate ambala" & ChrW(382) & "e"
    UpsertRow lo, existing, "OTKUI_FLD_KOL_AMB", "KOL. AMBALA" & ChrW(381) & "E"
    UpsertRow lo, existing, "OTKUI_FLD_KLASA", "KLASA ROBE"
    UpsertRow lo, existing, "OTKUI_SEG_KLASA_I", "I klasa"
    UpsertRow lo, existing, "OTKUI_SEG_KLASA_II", "II klasa"
    UpsertRow lo, existing, "OTKUI_KG_NETO", "NETO"
    UpsertRow lo, existing, "OTKUI_KG_UKUPNO", "UKUPNO"
    UpsertRow lo, existing, "OTKUI_LBL_VREDNOST", "VREDNOST"
    UpsertRow lo, existing, "OTKUI_LBL_OSTATAK", "NEISPLA" & ChrW(262) & "ENO"
    UpsertRow lo, existing, "OTKUI_FLD_BLOK", "Otvoreni otkupni blok"
    UpsertRow lo, existing, "OTKUI_FLD_AVANS", "ISPLATA IZ"
    UpsertRow lo, existing, "OTKUI_SEG_AVANS_VIRMAN", "Virman firme"
    UpsertRow lo, existing, "OTKUI_SEG_AVANS_OM", "Ke" & ChrW(353) & " iz OM avansa"
    UpsertRow lo, existing, "OTKUI_LBL_SALDO_OM", "OM AVANS"
    UpsertRow lo, existing, "OTKUI_FLD_FAKTURA", "Otvorena faktura"
    UpsertRow lo, existing, "OTKUI_ERR_KES_ISKLJUCEN", ChrW(10007) & " Ke" & ChrW(353) & " isplate su isklju" & ChrW(269) & "ene u Pode" & ChrW(353) & "avanjima."
    UpsertRow lo, existing, "OTKUI_FLD_PARCELA", "Parcela"
    UpsertRow lo, existing, "OTKUI_UNIT_KG", "kg"
    UpsertRow lo, existing, "OTKUI_UNIT_RSD_KG", "RSD/kg"
    UpsertRow lo, existing, "OTKUI_UNIT_RSD", "RSD"

    UpsertRow lo, existing, "OTKUI_BTN_OTKAZI", "Otka" & ChrW(382) & "i"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ", "Sa" & ChrW(269) & "uvaj"
    UpsertRow lo, existing, "OTKUI_BTN_SACUVAJ_PRINT", "Sa" & ChrW(269) & "uvaj i " & ChrW(353) & "tampaj"
    UpsertRow lo, existing, "OTKUI_BTN_FILTERI", "Filteri"
    UpsertRow lo, existing, "OTKUI_BTN_RED_PRINT", ChrW(352) & "tampaj list"
    UpsertRow lo, existing, "OTKUI_BTN_RED_STORNO", "Storniraj"
    UpsertRow lo, existing, "OTKUI_BTN_RED_PREUZMI", "Preuzmi"
    UpsertRow lo, existing, "OTKUI_BTN_RED_MARK", "Izaberi vi" & ChrW(353) & "e"
    UpsertRow lo, existing, "OTKUI_BTN_RED_SPEC", ChrW(352) & "tampaj specifikaciju"
    UpsertRow lo, existing, "OTKUI_BTN_RED_SPECDAT", "Po datumu"
    UpsertRow lo, existing, "OTKUI_LBL_OD", "OD"
    UpsertRow lo, existing, "OTKUI_LBL_DO", "DO"

    UpsertRow lo, existing, "OTKUI_PH_PRETRAGA", "Pretra" & ChrW(382) & "i broj, partnera, zbirnu..."
    UpsertRow lo, existing, "OTKUI_CHIP_DANAS", "Danas"
    UpsertRow lo, existing, "OTKUI_CHIP_NEDELJA", "Ova nedelja"
    UpsertRow lo, existing, "OTKUI_CHIP_SVE", "Sve"
    UpsertRow lo, existing, "OTKUI_CHIP_NEFAKT", "Nefakturisane"
    UpsertRow lo, existing, "OTKUI_CHIP_BEZZBIRNE", "Bez zbirne"
    UpsertRow lo, existing, "OTKUI_CHIP_OTKAZANE", "Otkazane"
    UpsertRow lo, existing, "OTKUI_CHIP_OTVORENE", "Neraspodeljene"
    UpsertRow lo, existing, "OTKUI_FLT_PERIOD", "PERIOD"
    UpsertRow lo, existing, "OTKUI_FLT_MESEC", "Ovaj mesec"
    UpsertRow lo, existing, "OTKUI_FLT_SUZI", "SUZI IZBOR"
    UpsertRow lo, existing, "OTKUI_FLT_SAMO_VRSTA", "Samo izabrana vrsta"
    UpsertRow lo, existing, "OTKUI_FLT_SAMO_PART", "Samo izabrani partner"
    UpsertRow lo, existing, "OTKUI_FLT_PONISTI", "Poni" & ChrW(353) & "ti filtere"
    UpsertRow lo, existing, "OTKUI_FLT_NEMA_VRSTE", "Prvo izaberi vrstu u Osnovnim podacima"
    UpsertRow lo, existing, "OTKUI_FLT_NEMA_PART", "Prvo izaberi partnera u Osnovnim podacima"

    UpsertRow lo, existing, "OTKUI_HD_BROJ", "BROJ"
    UpsertRow lo, existing, "OTKUI_HD_DATUM", "DATUM"
    UpsertRow lo, existing, "OTKUI_HD_PARTNER", "PARTNER"
    UpsertRow lo, existing, "OTKUI_HD_KG", "KG"
    UpsertRow lo, existing, "OTKUI_HD_VREDNOST", "VREDNOST"
    UpsertRow lo, existing, "OTKUI_HD_STATUS", "STATUS"
    UpsertRow lo, existing, "OTKUI_GRID_PRAZNO", "Nema dokumenata za izabrani filter."
    UpsertRow lo, existing, "OTKUI_GRID_PRIKAZI_SVE", "Prika" & ChrW(382) & "i sve"
    UpsertRow lo, existing, "OTKUI_LU_PRAZNO", "Nema unosa u ovoj smeni"
    UpsertRow lo, existing, "OTKUI_KPI_SUB_DOK", "dokumenata danas"
    UpsertRow lo, existing, "OTKUI_KPI_SUB_DUG", "otkupno mesto duguje"
    UpsertRow lo, existing, "OTKUI_KPI_SUB_POTRAZ", "u korist otkupnog mesta"
    UpsertRow lo, existing, "OTKUI_KPI_SUB_OK", "nema gre" & ChrW(353) & "aka"
    UpsertRow lo, existing, "OTKUI_SYNC_NIJE", "Nije jo" & ChrW(353) & " sinhronizovano"
    UpsertRow lo, existing, "OTKUI_FT_PRIKAZANO", "Prikazano"
    UpsertRow lo, existing, "OTKUI_FT_OD", "od"
    UpsertRow lo, existing, "OTKUI_FT_UKUPNO", "Ukupno"
    UpsertRow lo, existing, "OTKUI_FT_VREDNOST", "Vrednost"
    UpsertRow lo, existing, "OTKUI_STAT_SACUVANA", "Sa" & ChrW(269) & "uvana"
    UpsertRow lo, existing, "OTKUI_STAT_POSLATO", "Poslato"
    UpsertRow lo, existing, "OTKUI_STAT_OTKAZANA", "Otkazana"

    ' Desna kolona prikazuje SVE rezime (aktivni je obelezen), pa naslov nije
    ' vise "OSTALI". Stari kljuc ostaje u tabeli neupotrebljen - bezopasno.
    UpsertRow lo, existing, "OTKUI_LBL_OSTALI_REZIMI", "OSTALI RE" & ChrW(381) & "IMI"
    UpsertRow lo, existing, "OTKUI_LBL_REZIMI", "DOKUMENTI"
    UpsertRow lo, existing, "OTKUI_LBL_POSLEDNJI_UNOSI", "POSLEDNJI UNOSI"
    UpsertRow lo, existing, "OTKUI_LBL_SINHRONIZACIJA", "SINHRONIZACIJA"

    UpsertRow lo, existing, "OTKUI_ST_LEVO", "OM Zaovine " & ChrW(183) & " smena 1 " & ChrW(183) & " Dusan"
    UpsertRow lo, existing, "OTKUI_ST_SISTEMI", "Svi sistemi operativni"
    UpsertRow lo, existing, "OTKUI_ST_POMOC", "Pomo" & ChrW(263) & " F9"
    UpsertRow lo, existing, "OTKUI_SMENA_1", "smena 1"

    UpsertRow lo, existing, "OTKUI_ERR_BROJ", ChrW(10007) & " Broj dokumenta je obavezan"
    UpsertRow lo, existing, "OTKUI_ERR_KOLICINA", ChrW(10007) & " Koli" & ChrW(269) & "ina mora biti > 0"
    UpsertRow lo, existing, "OTKUI_ERR_CENA", ChrW(10007) & " Cena mora biti > 0"
    UpsertRow lo, existing, "OTKUI_ERR_STANICA", ChrW(10007) & " Nije mogu" & ChrW(263) & "e preuzeti otkupno mesto:"
    ' --- unos otkupnog lista (modOtkupUnos) ---
    UpsertRow lo, existing, "OTKUNOS_ERR_OM", ChrW(10007) & " Izaberi otkupno mesto"
    UpsertRow lo, existing, "OTKUNOS_ERR_KOOP", ChrW(10007) & " Izaberi ili unesi kooperanta"
    UpsertRow lo, existing, "OTKUNOS_ERR_VRSTA", ChrW(10007) & " Izaberi vrstu vo" & ChrW(263) & "a"
    UpsertRow lo, existing, "OTKUNOS_ERR_SORTA", ChrW(10007) & " Izaberi sortu vo" & ChrW(263) & "a"
    UpsertRow lo, existing, "OTKUNOS_ERR_KOLICINA_II", ChrW(10007) & " Unesi koli" & ChrW(269) & "inu za II klasu"
    UpsertRow lo, existing, "OTKUNOS_ERR_CENA_II", ChrW(10007) & " Unesi cenu za II klasu"
    UpsertRow lo, existing, "OTKUNOS_ERR_GAJBE_I", ChrW(10007) & " Unesi broj gajbi za I klasu"
    UpsertRow lo, existing, "OTKUNOS_ERR_GAJBE_II", ChrW(10007) & " Unesi broj gajbi za II klasu"
    UpsertRow lo, existing, "OTKUNOS_ERR_TARA_VECA", "je ve" & ChrW(263) & "a ili jednaka bruto te" & ChrW(382) & "ini " & ChrW(8212) & " proveri broj gajbi"
    UpsertRow lo, existing, "OTKUNOS_ASK_PARCELA_1", "Kultura parcele"
    UpsertRow lo, existing, "OTKUNOS_ASK_PARCELA_2", "ne odgovara izabranoj vrsti"
    UpsertRow lo, existing, "OTKUNOS_MSG_NIJE_HLADNJACA", "Napomena: ovaj unos nije autohladnja" & ChrW(269) & "a lanac " & ChrW(8212) & " palete stornirane prijemnice NISU prevezane:"
    UpsertRow lo, existing, "OTKUNOS_MSG_NEMA_PRIJEMNICE", "Novi lanac nije kreirao prijemnicu " & ChrW(8212) & " palete NISU prevezane."
    UpsertRow lo, existing, "OTKUNOS_MSG_PALETE_PREVEZANE", "Palete prevezane:"
    UpsertRow lo, existing, "OTKUNOS_MSG_PALETE_NISU", ChrW(10007) & " Auto-prevezivanje paleta nije uspelo:"
    UpsertRow lo, existing, "OTKUI_ASK_PREKORACENJE_1", "Blok prelazi ostatak otpremnice za"
    UpsertRow lo, existing, "OTKUI_ASK_PREKORACENJE_2", ChrW(8212) & " ipak upisati?"
    UpsertRow lo, existing, "OTKUNOS_MSG_UPISAN", ChrW(10003) & " Otkupni list sa" & ChrW(269) & "uvan:"

    ' --- unos dokumenata (modDokUnos): otpremnica, zbirna, prijemnica ---
    UpsertRow lo, existing, "DOKUNOS_ERR_VOZAC", ChrW(10007) & " Izaberi voza" & ChrW(269) & "a"
    UpsertRow lo, existing, "DOKUNOS_MSG_UPISANA_OTP", ChrW(10003) & " Otpremnica sa" & ChrW(269) & "uvana:"
    UpsertRow lo, existing, "OTKUI_MSG_UPISANO", ChrW(10003) & " Dokument sa" & ChrW(269) & "uvan:"
    UpsertRow lo, existing, "DOKUNOS_MSG_ZBIRNA_NIJE", ChrW(10007) & " Zbirna NIJE kreirana automatski " & ChrW(8212) & " unesi je ru" & ChrW(269) & "no (rezim Zbirna)."
    UpsertRow lo, existing, "DOKUNOS_MSG_VISE_ISPRAVKI", ChrW(10007) & " Vi" & ChrW(353) & "e ispravki na " & ChrW(269) & "ekanju za ovaj tip " & ChrW(8212) & " prevezivanje NIJE ura" & ChrW(273) & "eno. Re" & ChrW(353) & "i kroz Osiro" & ChrW(269) & "eni dokumenti."
    UpsertRow lo, existing, "DOKUNOS_ASK_ISPRAVKA_1", ChrW(268) & "eka ISPRAVKA za stornirano"
    UpsertRow lo, existing, "DOKUNOS_ASK_ISPRAVKA_2", "Da li je upravo snimljeni dokument ZAMENA za njega?"
    UpsertRow lo, existing, "DOKUNOS_MSG_ISPRAVKA_OK", ChrW(10003) & " Ispravka zavr" & ChrW(353) & "ena:"
    UpsertRow lo, existing, "DOKUNOS_MSG_ISPRAVKA_NIJE", ChrW(10007) & " Ispravka nije zavr" & ChrW(353) & "ena automatski:"
    ' --- zbirna (F3) i prijemnica (F4) ---
    UpsertRow lo, existing, "DOKUNOS_ERR_KUPAC", ChrW(10007) & " Izaberi kupca"
    UpsertRow lo, existing, "DOKUNOS_ERR_BROJ_ZBIRNE", ChrW(10007) & " Unesi broj zbirne"
    UpsertRow lo, existing, "DOKUNOS_ERR_IZVOR_KL2", ChrW(10007) & " Izvor (otpremnice) ima Klasu II " & ChrW(8212) & " uklju" & ChrW(269) & "i " & ChrW(8222) & "Dve klase" & ChrW(8220) & " i unesi Kl.II, ina" & ChrW(269) & "e bi bila izgubljena u zbirnoj."
    UpsertRow lo, existing, "DOKUNOS_ERR_ZBIRNA_NEMA_1", ChrW(10007) & " Zbirna"
    UpsertRow lo, existing, "DOKUNOS_ERR_ZBIRNA_NEMA_2", "ne postoji u sistemu " & ChrW(8212) & " prvo unesi zbirnu otpremnicu."
    UpsertRow lo, existing, "DOKUNOS_ASK_ZBIRNA_NEMA", "Ipak snimiti prijemnicu sa ovim brojem zbirne?"
    UpsertRow lo, existing, "DOKUNOS_ASK_DUPLA_PRIJ_1", "PA" & ChrW(381) & "NJA: zbirna"
    UpsertRow lo, existing, "DOKUNOS_ASK_DUPLA_PRIJ_2", "ve" & ChrW(263) & " ima aktivnu prijemnicu"
    UpsertRow lo, existing, "DOKUNOS_ASK_DUPLA_PRIJ_3", "Pravilo je 1 zbirna = 1 prijemnica, pa ovo li" & ChrW(269) & "i na DUPLI UNOS. Ipak snimiti?"
    UpsertRow lo, existing, "DOKUNOS_MSG_UPISANA_ZBR", ChrW(10003) & " Zbirna sa" & ChrW(269) & "uvana:"
    UpsertRow lo, existing, "DOKUNOS_MSG_UPISANA_PRIJ", ChrW(10003) & " Prijemnica sa" & ChrW(269) & "uvana:"
    ' --- unos novca i ambalaze (modNovacUnos): isplate F5, uplate F6, reversi F7 ---
    UpsertRow lo, existing, "NOVUNOS_ERR_NOVAC", ChrW(10007) & " Unesi iznos ve" & ChrW(263) & "i od nule"
    UpsertRow lo, existing, "NOVUNOS_ERR_KOL_AMB", ChrW(10007) & " Unesi koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e"
    UpsertRow lo, existing, "NOVUNOS_ERR_SMER", ChrW(10007) & " Izaberi smer reversa " & ChrW(8212) & " bez njega se ne zna ko koga zadu" & ChrW(382) & "uje."
    UpsertRow lo, existing, "NOVUNOS_ERR_SMER_KOOP", ChrW(10007) & " Za izdavanje/prijem ambala" & ChrW(382) & "e izaberi KOOPERANTA kao partnera."
    UpsertRow lo, existing, "NOVUNOS_ERR_VOZAC_OM", ChrW(10007) & " Revers firma" & ChrW(8212) & "OM ide preko voza" & ChrW(269) & "a " & ChrW(8212) & " izaberi voza" & ChrW(269) & "a."
    UpsertRow lo, existing, "NOVUNOS_ERR_VECI_OD_OSTATKA", ChrW(10007) & " Iznos je ve" & ChrW(263) & "i od neispla" & ChrW(263) & "enog ostatka bloka:"
    UpsertRow lo, existing, "NOVUNOS_ERR_VECI_OD_FAKTURE", ChrW(10007) & " Uplata je ve" & ChrW(263) & "a od preostalog iznosa fakture:"
    UpsertRow lo, existing, "NOVUNOS_ERR_PARTNER_NEIZABRAN", ChrW(10007) & " Izaberi partnera IZ LISTE " & ChrW(8212) & " ukucano ime nije prepoznato, pa dokument ne bi bio vezan za njega."
    UpsertRow lo, existing, "NOVUNOS_ERR_BLOK_NEIZABRAN", ChrW(10007) & " Izaberi otkupni blok IZ LISTE " & ChrW(8212) & " ovako bi isplata bila knji" & ChrW(382) & "ena kao avans."
    UpsertRow lo, existing, "NOVUNOS_ERR_FAKTURA_NEIZABRANA", ChrW(10007) & " Izaberi fakturu IZ LISTE " & ChrW(8212) & " ovako bi uplata bila knji" & ChrW(382) & "ena kao avans i faktura bi ostala otvorena."
    ' --- kapije vlasnistva i trenutnog ostatka (modNovac); dize ih i core ---
    UpsertRow lo, existing, "NOVAC_ERR_BLOK_NEMA", ChrW(10007) & " Otkupni blok ne postoji:"
    UpsertRow lo, existing, "NOVAC_ERR_BLOK_DUPLI", ChrW(10007) & " Dupli OtkupID " & ChrW(8212) & " target nije jednozna" & ChrW(269) & "an, pokreni proveru integriteta:"
    UpsertRow lo, existing, "NOVAC_ERR_BLOK_STORNIRAN", ChrW(10007) & " Otkupni blok je storniran:"
    UpsertRow lo, existing, "NOVAC_ERR_BLOK_TUDJ_KOOP", ChrW(10007) & " Otkupni blok pripada DRUGOM kooperantu:"
    UpsertRow lo, existing, "NOVAC_ERR_BLOK_TUDJ_OM", ChrW(10007) & " Otkupni blok je sa DRUGOG otkupnog mesta:"
    UpsertRow lo, existing, "NOVAC_ERR_FAK_NEMA", ChrW(10007) & " Faktura ne postoji:"
    UpsertRow lo, existing, "NOVAC_ERR_FAK_DUPLA", ChrW(10007) & " Dupli FakturaID " & ChrW(8212) & " target nije jednozna" & ChrW(269) & "an:"
    UpsertRow lo, existing, "NOVAC_ERR_FAK_STORNIRANA", ChrW(10007) & " Faktura je stornirana:"
    UpsertRow lo, existing, "NOVAC_ERR_FAK_TUDJ_KUPAC", ChrW(10007) & " Faktura pripada DRUGOM kupcu:"
    UpsertRow lo, existing, "NOVAC_ERR_FAK_VEC_PLACENA", ChrW(10007) & " Faktura je ve" & ChrW(263) & _
              " u potpunosti pla" & ChrW(263) & "ena " & ChrW(8212) & " nema " & ChrW(353) & "ta da se uplati:"
    UpsertRow lo, existing, "NOVAC_ERR_AVANS_PREKO", ChrW(10007) & " Isplata prelazi avans saldo otkupnog mesta. Raspolo" & ChrW(382) & "ivo:"
    UpsertRow lo, existing, "NOVUNOS_BEZ_BROJA", "(bez broja)"
    UpsertRow lo, existing, "NOVUNOS_NAP_FAKTURA", "Uplata po fakturi:"
    UpsertRow lo, existing, "NOVUNOS_NAP_AVANS_KUP", "Avans kupca"
    UpsertRow lo, existing, "NOVUNOS_MSG_UPISANA_ISPL", ChrW(10003) & " Isplata sa" & ChrW(269) & "uvana:"
    UpsertRow lo, existing, "NOVUNOS_MSG_UPISANA_UPL", ChrW(10003) & " Uplata sa" & ChrW(269) & "uvana:"
    UpsertRow lo, existing, "NOVUNOS_MSG_UPISAN_REV", ChrW(10003) & " Revers sa" & ChrW(269) & "uvan:"
    UpsertRow lo, existing, "OTKUI_ERR_NEMA_REDA", ChrW(10007) & " Prvo izaberi red u listi"
    UpsertRow lo, existing, "OTKUI_ERR_NEMA_DOK", ChrW(10007) & " Nema nestorniranog dokumenta broj"
    UpsertRow lo, existing, "OTKUI_ERR_NEMA_OTP", ChrW(10007) & " Izaberi otpremnicu (ili vi" & ChrW(353) & "e njih preko " & ChrW(8222) & "Izaberi vi" & ChrW(353) & "e" & ChrW(8220) & ")"
    UpsertRow lo, existing, "OTKUI_ERR_NEMA_FILT", ChrW(10007) & " Lista je prazna " & ChrW(8212) & " nema " & ChrW(353) & "ta da se " & ChrW(353) & "tampa"
    UpsertRow lo, existing, "OTKUI_MSG_SPEC", ChrW(10003) & " Specifikacija poslata na " & ChrW(353) & "tampu, otpremnica:"
    UpsertRow lo, existing, "OTKUI_ERR_STORNO", ChrW(10007) & " Storno nije uspeo:"
    UpsertRow lo, existing, "OTKUI_ERR_RADNJA", ChrW(10007) & " Radnja nije uspela:"
    UpsertRow lo, existing, "OTKUI_MSG_STAMPA", ChrW(10003) & " Poslato na " & ChrW(353) & "tampu:"
    UpsertRow lo, existing, "OTKUI_MSG_STORNIRANO", ChrW(10003) & " Storniran dokument"
    UpsertRow lo, existing, "OTKUI_ASK_PREUZMI", "Preuzeti blok br."
    UpsertRow lo, existing, "OTKUI_ASK_PREUZMI2", "na otpremnicu"
    UpsertRow lo, existing, "OTKUI_MSG_PREUZET", ChrW(10003) & " Preuzet blok"
    UpsertRow lo, existing, "OTKUI_ERR_PREUZMI", ChrW(10007) & " Preuzimanje nije uspelo (cilj je mo" & ChrW(382) & "da storniran):"
    UpsertRow lo, existing, "OTKUI_ERR_NEMA_AKT_OTP", ChrW(10007) & " Prvo izaberi ciljnu otpremnicu u listi Otpremnice"
    UpsertRow lo, existing, "OTKUI_ASK_STORNO", "Stornirati ceo otkup br."
    UpsertRow lo, existing, "OTKUI_ASK_STORNO2", "?" & vbCrLf & _
              "Storno obuhvata SVE klase istog dokumenta."
    ' --- F8 Storno centar (modStornoDok + ekran F8) ---
    UpsertRow lo, existing, "STORNO_TIP_OTKUP", "otkupni list"
    UpsertRow lo, existing, "STORNO_TIP_OTPREMNICA", "otpremnicu"
    UpsertRow lo, existing, "STORNO_TIP_ZBIRNA", "zbirnu"
    UpsertRow lo, existing, "STORNO_TIP_PRIJEMNICA", "prijemnicu"
    UpsertRow lo, existing, "STORNO_TIP_ISPLATA", "isplatu"
    UpsertRow lo, existing, "STORNO_TIP_UPLATA", "uplatu kupca"
    UpsertRow lo, existing, "STORNO_TIP_FAKTURA", "fakturu"
    UpsertRow lo, existing, "STORNO_TIP_IZVOD", "CEO izvod"
    UpsertRow lo, existing, "STORNO_TIP_REVERS", "revers"
    UpsertRow lo, existing, "STORNO_TIP_REV_IZD_KOOP", "revers izdavanje kooperantu"
    UpsertRow lo, existing, "STORNO_TIP_REV_PRI_KOOP", "revers povrat od kooperanta"
    UpsertRow lo, existing, "STORNO_TIP_REV_IZD_OM", "revers izdato OM (firma)"
    UpsertRow lo, existing, "STORNO_TIP_REV_PRI_OM", "revers prijem od OM (firma)"
    UpsertRow lo, existing, "STORNO_MSG_OK", ChrW(10003) & " Stornirano"
    UpsertRow lo, existing, "STORNO_MSG_ZBIRNA_PRIJ", "Zbirna je stornirana, ali AKTIVNA prijemnica ostaje vezana za nju " & _
              ChrW(8212) & " sledljivost je prekinuta. Kad unese" & ChrW(353) & "te novu zbirnu, prevezite prijemnicu:"
    UpsertRow lo, existing, "STORNO_ERR_NEMA_BROJA", ChrW(10007) & " Red nema broj dokumenta"
    UpsertRow lo, existing, "STORNO_ERR_NEMA_DOK", ChrW(10007) & " Nema nestorniranog dokumenta broj"
    UpsertRow lo, existing, "STORNO_ERR_NEMA_SMERA", ChrW(10007) & " Revers bez smera " & ChrW(8212) & " " & _
              ChrW(269) & "etiri smera dele isti brojevni niz"
    UpsertRow lo, existing, "STORNO_ERR_NEMA_ISHODA", ChrW(10007) & " Nije izabran ishod storna izvoda"
    UpsertRow lo, existing, "STORNO_ERR_NEPOZNAT_TIP", ChrW(10007) & " Nepoznat tip dokumenta:"
    UpsertRow lo, existing, "STORNO_ERR_RAZRESENJE", ChrW(10007) & " Gre" & ChrW(353) & "ka pri razre" & ChrW(353) & "avanju dokumenta:"
    UpsertRow lo, existing, "STORNO_ERR_NEUSPEH", ChrW(10007) & " Storno nije uspeo:"
    UpsertRow lo, existing, "STORNO_ASK", "Stornirati"
    UpsertRow lo, existing, "STORNO_ASK_IZVOD", "Stornirati CEO izvod?"
    UpsertRow lo, existing, "STORNO_ASK_IZVOD_PDF", "Da li je PDF izvoda bio ISPRAVAN?" & vbCrLf & vbCrLf & _
              "DA = samo je mapiranje pogre" & ChrW(353) & "no " & ChrW(8212) & _
              " stavke se vra" & ChrW(263) & "aju u " & ChrW(8222) & "za obradu" & ChrW(8220) & _
              ", PDF se NE uvozi ponovo." & vbCrLf & vbCrLf & _
              "NE = PDF je bio lo" & ChrW(353) & " ili korumpiran " & ChrW(8212) & _
              " izvod se gasi, uvezi ga PONOVO iz ispravnog PDF-a." & vbCrLf & vbCrLf & _
              "OTKAZI = odustani."
    ' --- ekran Storno (v6-ui-142) ---
    UpsertRow lo, existing, "OTKUI_NAV_STORNO", "Storno"
    UpsertRow lo, existing, "OTKUI_SCRST_SUB", "Pregled posledica pre odluke"
    UpsertRow lo, existing, "OTKUI_SCRST_LISTA", "Otkupni listovi"
    UpsertRow lo, existing, "OTKUI_SEG_ST_SVI", "Svi"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_ST_SVI", "Svi aktivni dokumenti"
    UpsertRow lo, existing, "OTKUI_ERR_LISTA", "Lista se nije u" & ChrW(269) & "itala"
    UpsertRow lo, existing, "OTKUI_HD_TIP", "TIP"
    UpsertRow lo, existing, "OTKUI_SCRST_IZBOR", "IZABRAN DOKUMENT"
    UpsertRow lo, existing, "OTKUI_SCRST_NEMA", "Izaberi red u listi da vidi" & ChrW(353) & " posledice"
    UpsertRow lo, existing, "OTKUI_SCRST_EFEKAT", "EFEKAT STORNA PO MODU"
    UpsertRow lo, existing, "OTKUI_SCRST_PALETE", "PALETE"
    UpsertRow lo, existing, "OTKUI_SCRST_BEZ_PALETA", "nema vezanih paleta"
    UpsertRow lo, existing, "OTKUI_SCRST_NEDIRAJ", "Ne diraj palete"
    UpsertRow lo, existing, "OTKUI_SCRST_BLOKOVI", "otkupnih blokova"
    ' cetiri moda: natpis dugmeta + objasnjenje ISPOD njega. Isti tekst koji je
    ' do v6-ui-142 zivotario u dva MsgBox-a (STORNO_ASK_MOD_1 / _2), samo sto
    ' se sada sva cetiri odgovora vide ISTOVREMENO, uz posledice iznad.
    UpsertRow lo, existing, "OTKUI_SCRST_B_ISPRAVKA", "Pogre" & ChrW(353) & "an unos"
    UpsertRow lo, existing, "OTKUI_SCRST_H_ISPRAVKA", "isti doga" & ChrW(273) & "aj " & ChrW(8212) & " storniraj pa unesi ispravan"
    UpsertRow lo, existing, "OTKUI_SCRST_B_DUPLI", "Duplikat"
    UpsertRow lo, existing, "OTKUI_SCRST_H_DUPLI", "nikad nije trebalo da postoji " & ChrW(8212) & " bez zamene"
    UpsertRow lo, existing, "OTKUI_SCRST_B_PONISTI", "Ni" & ChrW(353) & "ta se nije desilo"
    UpsertRow lo, existing, "OTKUI_SCRST_H_PONISTI", "fizi" & ChrW(269) & "ki tok se poni" & ChrW(353) & "tava"
    UpsertRow lo, existing, "OTKUI_SCRST_B_KASNIJE", "Re" & ChrW(353) & "i kasnije"
    UpsertRow lo, existing, "OTKUI_SCRST_H_KASNIJE", "zapamti kao nedovr" & ChrW(353) & "eno"
    UpsertRow lo, existing, "OTKUI_SCRST_B_STORNO", "Storniraj"
    UpsertRow lo, existing, "OTKUI_SCRST_H_STORNO", "obi" & ChrW(269) & "an storno, bez zamene"
    UpsertRow lo, existing, "OTKUI_SCRST_B_REV_ISPR", "Ispravka"
    UpsertRow lo, existing, "OTKUI_SCRST_H_REV_ISPR", "storniraj stari, unesi novi (veza staro" & ChrW(8594) & "novo)"
    ' natpisi prekidaca tipova u Stornu - kratki, jer ih je deset u jednom redu
    UpsertRow lo, existing, "OTKUI_SEG_ST_OTKUP", "Otkupni"
    UpsertRow lo, existing, "OTKUI_SEG_ST_OTP", "Otpremnice"
    UpsertRow lo, existing, "OTKUI_SEG_ST_ZBR", "Zbirne"
    UpsertRow lo, existing, "OTKUI_SEG_ST_PRJ", "Prijemnice"
    UpsertRow lo, existing, "OTKUI_SEG_ST_ISP", "Isplate"
    UpsertRow lo, existing, "OTKUI_SEG_ST_UPL", "Uplate"
    UpsertRow lo, existing, "OTKUI_SEG_ST_REV", "Reversi"
    UpsertRow lo, existing, "OTKUI_SEG_ST_FAK", "Fakture"
    UpsertRow lo, existing, "OTKUI_SEG_ST_IZV", "Izvodi"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_FAKTURA", "Postoje" & ChrW(263) & "e fakture"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_IZVOD", "Uvezeni bankovni izvodi"
    UpsertRow lo, existing, "OTKUI_HD_IZNOS", "IZNOS"
    UpsertRow lo, existing, "OTKUI_HD_RACUN", "RA" & ChrW(268) & "UN"
    UpsertRow lo, existing, "OTKUI_HD_STAVKI", "STAVKI"
    ' --- framework ispravke posle storna (Faza D/13) ---
    UpsertRow lo, existing, "STORNO_ASK_REVERS", ChrW(352) & "ta radi" & ChrW(353) & " sa reversom?" & vbCrLf & vbCrLf & _
              "DA = obi" & ChrW(269) & "an STORNO (saldo se koriguje)" & vbCrLf & _
              "NE = ISPRAVKA (storniraj stari, unesi novi " & ChrW(8212) & " veza staro" & ChrW(8594) & "novo)" & vbCrLf & _
              "OTKAZI = odustani"
    UpsertRow lo, existing, "STORNO_ASK_MOD_1", ChrW(352) & "ta storno POSLOVNO zna" & ChrW(269) & "i?" & vbCrLf & vbCrLf & _
              "DA = ISPRAVKA: pogre" & ChrW(353) & "an unos, isti doga" & ChrW(273) & "aj " & ChrW(8212) & _
              " storniraj stari pa unesi ispravan; veze i prera" & ChrW(269) & "un idu automatski" & vbCrLf & vbCrLf & _
              "NE = ne" & ChrW(353) & "to drugo (bira se u slede" & ChrW(263) & "em koraku)" & vbCrLf & vbCrLf & _
              "OTKAZI = odustani, ni" & ChrW(353) & "ta se ne menja"
    UpsertRow lo, existing, "STORNO_ASK_MOD_2", ChrW(352) & "ta onda?" & vbCrLf & vbCrLf & _
              "DA = DUPLIKAT: dokument nikad nije trebalo da postoji " & ChrW(8212) & _
              " skini posledice, nema zamene" & vbCrLf & vbCrLf & _
              "NE = PONI" & ChrW(352) & "TENJE: fizi" & ChrW(269) & "ki tok se poni" & ChrW(353) & "tava, nema novog dokumenta" & vbCrLf & vbCrLf & _
              "OTKAZI = RE" & ChrW(352) & "I KASNIJE: zapamti kao nedovr" & ChrW(353) & "eno (Osiro" & ChrW(263) & "eni dokumenti)"
    UpsertRow lo, existing, "STORNO_ASK_PALETE", "Da li palete da OSTANU vezane za storniranu prijemnicu?" & vbCrLf & vbCrLf & _
              "DA = ne diraj palete (roba je fizi" & ChrW(269) & "ki tu, samo je dokument pogre" & ChrW(353) & "an)" & vbCrLf & _
              "NE = odve" & ChrW(382) & "i palete (roba nije primljena)"
    UpsertRow lo, existing, "STORNO_ASK_PONISTI", "PONI" & ChrW(352) & "TITI dokument i SVE gore navedeno?"
    UpsertRow lo, existing, "STORNO_MSG_ISPRAVKA_DALJE", "SLEDE" & ChrW(262) & "E: unesi i snimi NOVI dokument (normalno)." & vbCrLf & _
              "Polja su ve" & ChrW(263) & " popunjena iz storniranog " & ChrW(8212) & " promeni samo ono " & ChrW(353) & "to je bilo pogre" & ChrW(353) & "no." & vbCrLf & _
              "Prevezivanje i prera" & ChrW(269) & "un se rade AUTOMATSKI po snimanju."
    UpsertRow lo, existing, "STORNO_MSG_ODUSTANAK", "Odustalo se " & ChrW(8212) & " ni" & ChrW(353) & "ta nije promenjeno."
    UpsertRow lo, existing, "STORNO_ASK_BLOKOVI_1", "Uz ovaj dokument visi"
    UpsertRow lo, existing, "STORNO_ASK_BLOKOVI_2", " otkupnih blokova:"
    UpsertRow lo, existing, "STORNO_ASK_BLOKOVI_3", "Stornirati i NJIH?" & vbCrLf & vbCrLf & _
              "DA = roba nije otkupljena " & ChrW(8212) & " blokovi padaju sa dokumentom" & vbCrLf & _
              "NE = blokovi ostaju (oslobo" & ChrW(273) & "eni; vide se u listi Izgubljeni)"
    UpsertRow lo, existing, "STORNO_MSG_BLOKOVI_OK", ChrW(10003) & " Stornirano otkupnih blokova:"
    UpsertRow lo, existing, "STORNO_ERR_BLOKOVI", ChrW(10007) & " Storno otkupnih blokova nije uspeo." & vbCrLf & vbCrLf & _
              "Dokument JESTE storniran. Blokove storniraj ru" & ChrW(269) & "no " & ChrW(8212) & _
              " zadatak je zabele" & ChrW(382) & "en u: Oporavak " & ChrW(8594) & " Nedovr" & ChrW(353) & "eno."
    ' --- ispravka prijemnice (prevezivanje paleta) ---
    UpsertRow lo, existing, "DOKUNOS_MSG_VISE_ISPRAVKI_PRIJ", "Postoji VI" & ChrW(352) & "E ispravki prijemnice na " & ChrW(269) & "ekanju." & vbCrLf & _
              "Palete NISU automatski prevezane (da se ne pove" & ChrW(382) & "e pogre" & ChrW(353) & "na)." & vbCrLf & _
              "Re" & ChrW(353) & "i kroz: Osiro" & ChrW(263) & "eni dokumenti."
    UpsertRow lo, existing, "DOKUNOS_ASK_ISPRAVKA_PRIJ_1", ChrW(268) & "eka ISPRAVKA za storniranu prijemnicu"
    UpsertRow lo, existing, "DOKUNOS_ASK_ISPRAVKA_PRIJ_2", "Da li je OVAJ unos zamena za nju?" & vbCrLf & vbCrLf & _
              "DA = ispravka (palete se prevezuju na novu prijemnicu)" & vbCrLf & _
              "NE = obi" & ChrW(269) & "an, nepovezan unos (normalna paletizacija)"
    UpsertRow lo, existing, "DOKUNOS_ASK_ISPRAVKA_ZBIRNA", "Zbirna je promenjena. Da li je ovo i dalje ISPRAVKA?" & vbCrLf & vbCrLf & _
              "DA = ispravka (palete se prevezuju i dobijaju novu zbirnu)" & vbCrLf & _
              "NE = nov, nepovezan unos (normalna paletizacija)" & vbCrLf & _
              "OTKAZI = ne snimaj jo" & ChrW(353)
    UpsertRow lo, existing, "DOKUNOS_MSG_PALETE_PREVEZANE", ChrW(10003) & " Palete prevezane:"
    UpsertRow lo, existing, "DOKUNOS_MSG_PALETE_NISU", ChrW(10007) & " Prevezivanje paleta nije uspelo " & ChrW(8212) & _
              " uradi ru" & ChrW(269) & "no (Osiro" & ChrW(263) & "eni dokumenti " & ChrW(8594) & " Palete):"
    UpsertRow lo, existing, "DOKUNOS_ERR_ISPRAVKA_NECITLJIVA", ChrW(10007) & " Ne mo" & ChrW(382) & "e se utvrditi da li ISPRAVKA " & _
              ChrW(269) & "eka na ovu prijemnicu." & vbCrLf & vbCrLf & _
              "Upis je zaustavljen namerno: da je nastavljen, nova prijemnica bi dobila SVE" & ChrW(381) & "E palete, " & _
              "a stare bi ostale osiro" & ChrW(263) & "ene." & vbCrLf & _
              "Proveri stanje u: Oporavak " & ChrW(8594) & " Nedovr" & ChrW(353) & "eno."
    UpsertRow lo, existing, "DOKUNOS_ERR_BROJ_DVOSMISLEN", ChrW(10007) & " Broj prijemnice nije jednozna" & ChrW(269) & "an " & _
              ChrW(8212) & " isti broj nose dokumenta VI" & ChrW(352) & "E kupaca:"
    UpsertRow lo, existing, "DOKUNOS_ERR_BROJ_DVOSMISLEN2", "Prevezivanje paleta ide PO BROJU, pa se ne zna na koji dokument." & vbCrLf & _
              "Palete su ostale na staroj prijemnici " & ChrW(8212) & " prevezi ih ru" & ChrW(269) & "no kroz Oporavak, " & _
              "posle ispravke broja."
    ' --- hladnjaca ispravka posle storna otkupa (F1) ---
    UpsertRow lo, existing, "OTKUI_MSG_HLAD_LANAC", "Otkup storniran (autohladnja" & ChrW(269) & "a: ceo lanac oboren)."
    UpsertRow lo, existing, "OTKUI_MSG_HLAD_PALETE", "Paletizovana prijemnica:"
    UpsertRow lo, existing, "OTKUI_ASK_HLAD", ChrW(352) & "ta dalje sa paletama?" & vbCrLf & vbCrLf & _
              "DA = ISPRAVKA: izmeni gre" & ChrW(353) & "ku, palete idu na nov lanac" & vbCrLf & _
              "NE = DUPLI UNOS: nije primljeno 2x, skini stavke" & vbCrLf & _
              "OTKAZI = ni" & ChrW(353) & "ta sada (palete ostaju osiro" & ChrW(263) & "ene)"
    UpsertRow lo, existing, "OTKUI_MSG_HLAD_ISPRAVKA", ChrW(10003) & " Polja popunjena iz storniranog " & ChrW(8212) & _
              " izmeni gre" & ChrW(353) & "ku pa snimi"
    UpsertRow lo, existing, "OTKUI_MSG_HLAD_NISTA", "Ni" & ChrW(353) & "ta nije skinuto."
    UpsertRow lo, existing, "OTKUI_MSG_HLAD_OSIROCENE", "Palete su osiro" & ChrW(263) & "ene (i dalje broje robu)." & vbCrLf & _
              "Re" & ChrW(353) & "i ru" & ChrW(269) & "no: Oporavak " & ChrW(8594) & " Palete."
    ' --- ekran Oporavak (Faza D/14) ---
    UpsertRow lo, existing, "OTKUI_NAV_OPORAVAK", "Oporavak"
    UpsertRow lo, existing, "OTKUI_SCROPO_SUB", "Nedovr" & ChrW(353) & "eno, osiro" & ChrW(263) & "eni dokumenti i vra" & ChrW(263) & "anje storna"
    UpsertRow lo, existing, "OTKUI_SCROPO_LISTA", "Nedovr" & ChrW(353) & "eno"
    UpsertRow lo, existing, "OTKUI_SEG_OPO_NED", "Nedovr" & ChrW(353) & "eno"
    UpsertRow lo, existing, "OTKUI_SEG_OPO_PRI", "Osiro" & ChrW(263) & "ene prijem."
    UpsertRow lo, existing, "OTKUI_SEG_OPO_ZBR", "Zbirne (cilj)"
    UpsertRow lo, existing, "OTKUI_SEG_OPO_PAL", "Osiro" & ChrW(263) & ".palete"
    UpsertRow lo, existing, "OTKUI_SEG_OPO_CPR", "Prijemnice (cilj)"
    UpsertRow lo, existing, "OTKUI_SEG_OPO_UND", "Vrati storno"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_NEDOVRSENO", "Nedovr" & ChrW(353) & "eno " & ChrW(8212) & " sve " & ChrW(353) & "to " & ChrW(269) & "eka"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_OSIR_PRIJ", "Osiro" & ChrW(263) & "ene prijemnice (zbirna stornirana ili je nema)"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_CILJ_ZBIRNA", "Aktivne zbirne " & ChrW(8212) & " izaberi CILJ"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_OSIR_PAL", "Prijemnice sa osiro" & ChrW(263) & "enim paletama"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_CILJ_PRIJ", "Aktivne prijemnice " & ChrW(8212) & " izaberi CILJ"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_UNDO", "Storno operacije koje se mogu vratiti"
    UpsertRow lo, existing, "OTKUI_HDO_REF", "DOKUMENT"
    UpsertRow lo, existing, "OTKUI_HDO_VRSTA_PROB", "VRSTA PROBLEMA"
    UpsertRow lo, existing, "OTKUI_HDO_OPIS", "OPIS"
    UpsertRow lo, existing, "OTKUI_HDO_AKCIJA", "GDE SE RE" & ChrW(352) & "AVA"
    UpsertRow lo, existing, "OTKUI_HDO_OPID", "OPERACIJA"
    UpsertRow lo, existing, "OTKUI_HDO_VREME", "VREME"
    UpsertRow lo, existing, "OTKUI_HDO_TIPDOK", "TIP DOKUMENTA"
    UpsertRow lo, existing, "OTKUI_OPO_CILJEVI", "Ciljevi prevezivanja"
    UpsertRow lo, existing, "OTKUI_OPO_CILJ_ZBIRNA", "Zbirna:"
    UpsertRow lo, existing, "OTKUI_OPO_CILJ_PRIJ", "Prijemnica:"
    UpsertRow lo, existing, "OTKUI_OPO_KPI_NED", "Nedovr" & ChrW(353) & "eno"
    UpsertRow lo, existing, "OTKUI_OPO_KPI_OSIR", "Osiro" & ChrW(263) & "eno"
    UpsertRow lo, existing, "OTKUI_OPO_KPI_UNDO", "Za vra" & ChrW(263) & "anje"
    UpsertRow lo, existing, "OTKUI_BTN_OPO_PREVEZI", "Prevezi"
    UpsertRow lo, existing, "OTKUI_BTN_OPO_VRATI", "Vrati storno"
    UpsertRow lo, existing, "OTKUI_ASK_OPO_PRI", "Prevezati prijemnicu"
    UpsertRow lo, existing, "OTKUI_ASK_OPO_PAL", "Prevezati palete prijemnice"
    UpsertRow lo, existing, "OTKUI_ASK_OPO_NA", "na"
    UpsertRow lo, existing, "OTKUI_ASK_OPO_UNDO", "Vratiti storno:"
    UpsertRow lo, existing, "OTKUI_ASK_OPO_UNDO2", "Dokument se vra" & ChrW(263) & "a u AKTIVNO stanje, sa svim posledicama."
    UpsertRow lo, existing, "OTKUI_MSG_OPO_PREVEZANO", ChrW(10003) & " Prevezano:"
    UpsertRow lo, existing, "OTKUI_MSG_OPO_VRACENO", ChrW(10003) & " Storno vra" & ChrW(263) & "en:"
    UpsertRow lo, existing, "OTKUI_ERR_OPO_NEMA_ZBIRNE", ChrW(10007) & " Prvo izaberi ciljnu zbirnu u listi " & ChrW(8222) & "Zbirne (cilj)" & ChrW(8220)
    UpsertRow lo, existing, "OTKUI_ERR_OPO_NEMA_PRIJ", ChrW(10007) & " Prvo izaberi ciljnu prijemnicu u listi " & ChrW(8222) & "Prijemnice (cilj)" & ChrW(8220)
    UpsertRow lo, existing, "OTKUI_ERR_OPO_ISTA", ChrW(10007) & " Izvor i cilj su ista prijemnica"
    UpsertRow lo, existing, "OTKUI_ERR_OPO_PRI", ChrW(10007) & " Prevezivanje nije uspelo " & ChrW(8212) & " proveri da li je ciljna zbirna aktivna:"
    UpsertRow lo, existing, "OTKUI_ERR_OPO_PAL", ChrW(10007) & " Prevezivanje paleta nije uspelo."
    UpsertRow lo, existing, "OTKUI_ERR_OPO_UNDO", ChrW(10007) & " Vra" & ChrW(263) & "anje storna nije uspelo:"
    UpsertRow lo, existing, "OTKUI_HDO_VLASNIK", "VLASNIK"
    UpsertRow lo, existing, "OTKUI_HDO_GENERACIJA", "GENERACIJA"
    UpsertRow lo, existing, "OTKUI_ERR_OPO_DVOSMISLEN", ChrW(10007) & " Ciljni broj nije jednozna" & ChrW(269) & "an " & _
              ChrW(8212) & " isti broj nose dokumenta VI" & ChrW(352) & "E vlasnika:"
    UpsertRow lo, existing, "OTKUI_ERR_OPO_DVOSMISLEN2", "Prevezivanje ide PO BROJU, pa se ne zna na koji dokument." & vbCrLf & _
              "U listi ciljeva se vide oba reda " & ChrW(8212) & " razlikuju se po koloni VLASNIK." & vbCrLf & _
              "Ispravi broj jednog dokumenta, pa ponovi."
    UpsertRow lo, existing, "OTKUI_ERR_DATUM", ChrW(10007) & " Datum nije " & ChrW(269) & "itljiv " & ChrW(8212) & " upi" & ChrW(353) & "i ga kao 11.08.2026."
    UpsertRow lo, existing, "OTKUI_MSG_SNIMLJENO", ChrW(10003) & " Dokument spreman za upis"
    UpsertRow lo, existing, "OTKUI_MSG_PRINT", ChrW(353) & "tampa"
    UpsertRow lo, existing, "OTKUI_MSG_UCITANO", "U" & ChrW(269) & "itano:"
    UpsertRow lo, existing, "OTKUI_MSG_POMOC", "F9 " & ChrW(8212) & " pomo" & ChrW(263) & " jo" & ChrW(353) & " nije vezana."
    UpsertRow lo, existing, "OTKUI_TODO_NEVEZANO", "Nije vezano na postoje" & ChrW(263) & "u rutinu."
    UpsertRow lo, existing, "OTKUI_SCR_NEMA", "Ovaj ekran jo" & ChrW(353) & " nije preba" & ChrW(269) & "en na novi izgled."
    UpsertRow lo, existing, "OTKUI_SCR_ZABRANJEN", "Nemate dozvolu za ovu oblast."
    UpsertRow lo, existing, "OTKUI_SCRPAL_SUB", "Pregled paleta " & ChrW(8212) & " samo za " & ChrW(269) & "itanje"
    ' --- ekran Palete (P1) ---
    UpsertRow lo, existing, "OTKUI_HDP_KAPACITET", "KAPACITET"
    UpsertRow lo, existing, "OTKUI_HDP_PRERADJENO", "PRERA" & ChrW(272) & "ENO"
    UpsertRow lo, existing, "OTKUI_HDS_PRIJEMNICA", "BROJ PRIJEMNICE"
    UpsertRow lo, existing, "OTKUI_HD_BROJ_ZBIRNE", "BROJ ZBIRNE"
    UpsertRow lo, existing, "OTKUI_HDR_TIPGP", "GOTOV PROIZVOD"
    UpsertRow lo, existing, "OTKUI_HDR_KUTIJE", "KUTIJE"
    UpsertRow lo, existing, "OTKUI_HDR_KESE", "KESE"
    UpsertRow lo, existing, "OTKUI_SEG_PAL_PALETE", "Palete"
    UpsertRow lo, existing, "OTKUI_SEG_PAL_STAVKE", "Stavke palete"
    UpsertRow lo, existing, "OTKUI_SEG_PAL_PRERADE", "Prerade"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_PALETE", "Palete"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_PALSTAVKE", "Stavke palete"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_PRERADE", "Prera" & ChrW(273) & "ene palete"
    UpsertRow lo, existing, "OTKUI_BTN_PAL_PRINT", ChrW(352) & "tampaj list"
    UpsertRow lo, existing, "OTKUI_BTN_PAL_PDF", "PDF"
    UpsertRow lo, existing, "OTKUI_BTN_PAL_ZATVORI", "Zatvori paletu"
    UpsertRow lo, existing, "OTKUI_BTN_PAL_NEPOTPUNE", ChrW(352) & "tampaj nepotpune"
    UpsertRow lo, existing, "OTKUI_BTN_PRE_PRINT", ChrW(352) & "tampaj preradu"
    UpsertRow lo, existing, "OTKUI_BTN_PRE_STORNO", "Storniraj preradu"
    UpsertRow lo, existing, "OTKUI_PAL_AKTIVNA", "Aktivna paleta"
    UpsertRow lo, existing, "OTKUI_PAL_NEMA", "Nema izabrane palete " & ChrW(8212) & " izaberi je u listi Palete"
    UpsertRow lo, existing, "OTKUI_PAL_IZABRANA", "izabrana paleta"
    UpsertRow lo, existing, "OTKUI_ASK_PAL_ZATVORI", "Zatvoriti paletu br."
    UpsertRow lo, existing, "OTKUI_MSG_PAL_ZATVORENA", ChrW(10003) & " Zatvorena paleta"
    UpsertRow lo, existing, "OTKUI_ASK_PAL_STORNO", "Stornirati paletu br."
    UpsertRow lo, existing, "OTKUI_MSG_PAL_STORNIRANA", ChrW(10003) & " Stornirana paleta"
    UpsertRow lo, existing, "OTKUI_ERR_PAL_PRERADJENA", ChrW(10007) & " Paleta je prera" & ChrW(273) & "ena " & ChrW(8212) & " prvo storniraj preradu, pa se vra" & ChrW(263) & "a u lager"
    UpsertRow lo, existing, "OTKUI_MSG_PAL_NEPOTPUNE", ChrW(10003) & " Nepotpunih paleta poslato na izlaz:"
    UpsertRow lo, existing, "OTKUI_ASK_PRE_STORNO", "Stornirati preradu br."
    UpsertRow lo, existing, "OTKUI_ASK_PRE_STORNO2", "Palete gotovih proizvoda se vra" & ChrW(263) & "aju u lager."
    UpsertRow lo, existing, "OTKUI_MSG_PRE_STORNIRANA", ChrW(10003) & " Stornirana prerada"
    UpsertRow lo, existing, "OTKUI_SCRPAL_UKUPNO", "Ukupno paleta"
    UpsertRow lo, existing, "OTKUI_SCRPAL_OTVORENE", "Otvorene"
    UpsertRow lo, existing, "OTKUI_SCRPAL_GAJBICA", "Gajbica"
    UpsertRow lo, existing, "OTKUI_SCRPAL_FOOT", "Prikazano"
    UpsertRow lo, existing, "OTKUI_SCRPAL_LISTA", "Palete"
    UpsertRow lo, existing, "OTKUI_HDP_BROJ", "Broj"
    UpsertRow lo, existing, "OTKUI_HDP_GODINA", "Godina"
    UpsertRow lo, existing, "OTKUI_HDP_GAJBICA", "Gajbica"
    UpsertRow lo, existing, "OTKUI_HDP_NETO", "Neto kg"
    UpsertRow lo, existing, "OTKUI_HDP_BRUTO", "Bruto kg"
    UpsertRow lo, existing, "OTKUI_HDO_KUPAC", "Kupac"
    UpsertRow lo, existing, "OTKUI_HDO_UBLOK", "U blokovima"
    UpsertRow lo, existing, "OTKUI_HDO_OSTATAK", "Ostatak"
    UpsertRow lo, existing, "OTKUI_HD_CENA", "Cena"
    UpsertRow lo, existing, "OTKUI_SEG_LS_SVI", "Svi listovi"
    UpsertRow lo, existing, "OTKUI_SEG_LS_OTP", "Otpremnice"
    UpsertRow lo, existing, "OTKUI_SEG_LS_BLOK", "Blokovi otpremnice"
    UpsertRow lo, existing, "OTKUI_SEG_LS_LOST", "Izgubljeni"
    UpsertRow lo, existing, "OTKUI_SEG_LS_KOOP", "Kooperanti"
    UpsertRow lo, existing, "OTKUI_OTP_TRAKA", "Aktivna otpremnica"
    UpsertRow lo, existing, "OTKUI_OTP_NEMA", "Nema izabrane otpremnice " & ChrW(8212) & " izaberi je u listi Otpremnice"
    UpsertRow lo, existing, "OTKUI_OTP_UKUPNO", "Ukupno kg"
    UpsertRow lo, existing, "OTKUI_OTP_UBLOK", "U blokovima"
    UpsertRow lo, existing, "OTKUI_OTP_OSTATAK", "Ostatak"
    UpsertRow lo, existing, "OTKUI_OTP_CENA", "Cena"
    UpsertRow lo, existing, "OTKUI_OTP_AMB", "amb"
    UpsertRow lo, existing, "OTKUI_OTP_PO_OTP", "po otpremnici"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_BLOKOVI", "Blokovi otpremnice"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_LOST", "Izgubljeni blokovi"
    UpsertRow lo, existing, "OTKUI_GRID_TITLE_KOOP", "Kooperanti po iznosu otkupa"
    UpsertRow lo, existing, "OTKUI_HDK_RANG", "RANG"
    UpsertRow lo, existing, "OTKUI_HDK_KOOPERANT", "KOOPERANT"
    UpsertRow lo, existing, "OTKUI_HDK_IZNOS", "IZNOS RSD"
    UpsertRow lo, existing, "OTKUI_HD_OM", "OTKUPNO MESTO"
    UpsertRow lo, existing, "OTKUI_HDL_STARA", "STARA OTPREMNICA"
    InvalidateCache
End Sub

Private Sub UpsertRow(lo As ListObject, existing As Object, _
                      ByVal kljuc As String, ByVal tekst As String)
    If existing.Exists(kljuc) Then
        If CStr(lo.ListRows(existing(kljuc)).Range(2).Value) <> tekst Then
            lo.ListRows(existing(kljuc)).Range(2).Value = tekst
        End If
    Else
        Dim r As ListRow
        Set r = lo.ListRows.Add
        r.Range(1).Value = kljuc
        r.Range(2).Value = tekst
        existing(kljuc) = r.Index
    End If
End Sub
