Attribute VB_Name = "modPoruke"
Option Explicit

Public Function Poruka(ByVal kljuc As String) As String
    On Error GoTo EH
    Dim v As Variant
    v = LookupValue(TBL_PORUKE, COL_POR_KLJUC, kljuc, COL_POR_TEKST)
    If IsEmpty(v) Or IsNull(v) Or CStr(v) = "" Then
        Poruka = "[" & kljuc & "]"
    Else
        Poruka = CStr(v)
    End If
    Exit Function
EH:
    Poruka = "[" & kljuc & "]"
End Function

Public Sub SeedPoruke(lo As ListObject)
    If lo.ListRows.Count > 0 Then Exit Sub
    Dim r As ListRow
    Set r = lo.ListRows.Add
    r.Range(1).Value = "APP_MSG_GRESKA_PRI_POKRETANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri pokretanju aplikacije. Pogledajte log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_LBL_MAGACIN_IZDAVANJE_ROBE"
    r.Range(2).Value = "Magacin " & ChrW(8212) & " izdavanje robe i prijem od dobavlja" & ChrW(269) & "a"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_LBL_IZLAZ_IZDAVANJE_ROBE"
    r.Range(2).Value = "Izlaz " & ChrW(8212) & " Izdavanje robe kooperantu"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_LBL_ULAZ_PRIJEM_ROBE"
    r.Range(2).Value = "Ulaz " & ChrW(8212) & " Prijem robe od dobavlja" & ChrW(269) & "a"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_LBL_ZAVRSI_IZDAVANJE"
    r.Range(2).Value = "Zavr" & ChrW(353) & "i izdavanje"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_LBL_ZAVRSI_PRIJEM"
    r.Range(2).Value = "Zavr" & ChrW(353) & "i prijem"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_LBL_POPUNI_PAKOVANJE_FIELD"
    r.Range(2).Value = "Popuni 'Pakovanje' field u tblArtikli pre kori" & ChrW(353) & "cenja."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_MSG_POKUSAVATE_DODATI"
    r.Range(2).Value = "Poku" & ChrW(353) & "avate dodati:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_MSG_IZDAVANJE_ZAVRSENO"
    r.Range(2).Value = "Izdavanje zavr" & ChrW(353) & "eno:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_MSG_GRESKA_PRI_CUVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju izdavanja, promene vra" & ChrW(263) & "ene:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_MSG_PRIJEM_ZAVRSEN"
    r.Range(2).Value = "Prijem zavr" & ChrW(353) & "en:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_MSG_GRESKA_PRI_CUVANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju prijema, promene vra" & ChrW(263) & "ene:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "BANKA_LBL_GENERISI_CSV_COMMIT"
    r.Range(2).Value = "Generi" & ChrW(353) & "i CSV (Commit 3)"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "BANKA_LBL_UVOZ_TRANSAKCIJA_BANKARSKIH"
    r.Range(2).Value = "Uvoz transakcija iz bankarskih izvoda " & ChrW(8212) & " mapiranje na partnere"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_LBL_OPERATIVNI_UNOS_DOKUMENATA"
    r.Range(2).Value = "Operativni unos dokumenata, ambala" & ChrW(382) & "e i novca"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_ERR_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju dokumenata:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_UNOSI_SAMO_KLASA"
    r.Range(2).Value = "Unosi se samo II klasa: obri" & ChrW(353) & "ite koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e za I klasu."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_UNESITE_ISPRAVNU_KOLICINU"
    r.Range(2).Value = "Unesite ispravnu koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_UNESITE_ISPRAVNU_KOLICINU_2"
    r.Range(2).Value = "Unesite ispravnu koli" & ChrW(269) & "inu ambala" & ChrW(382) & "e za II klasu!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_TIP_AMBALAZE"
    r.Range(2).Value = "Tip ambala" & ChrW(382) & "e '"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_NEMA_UNETU_TEZINU"
    r.Range(2).Value = "' nema unetu te" & ChrW(382) & "inu gajbice"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_MATICNI_PODACI_TIP"
    r.Range(2).Value = "(Mati" & ChrW(269) & "ni podaci ? Tip ambala" & ChrW(382) & "e)."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_BRUTO_MOZE_PRETVORITI"
    r.Range(2).Value = "Bruto se ne mo" & ChrW(382) & "e pretvoriti u neto."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_TEZINA_AMBALAZE"
    r.Range(2).Value = "Te" & ChrW(382) & "ina ambala" & ChrW(382) & "e ("
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_JEDNAKA_BRUTO_TEZINI"
    r.Range(2).Value = "jednaka bruto te" & ChrW(382) & "ini ("
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_PROVERITE_BROJ_KOMADA"
    r.Range(2).Value = "Proverite broj komada ili tip ambala" & ChrW(382) & "e."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_BRUTO_KLASA_MOZE"
    r.Range(2).Value = "Bruto (II klasa) se ne mo" & ChrW(382) & "e pretvoriti u neto."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_TEZINA_AMBALAZE_KLASE"
    r.Range(2).Value = "Te" & ChrW(382) & "ina ambala" & ChrW(382) & "e II klase ("
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_GRESKA_PRI_CUVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju otpremnice. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_ERR_GRESKA"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_UNESITE_AMBALAZU_ILI"
    r.Range(2).Value = "Unesite ambala" & ChrW(382) & "u ili novac za OM ulaz."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_IZABERITE_TIP_AMBALAZE"
    r.Range(2).Value = "Izaberite tip ambala" & ChrW(382) & "e!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_NEDOVOLJNO_AVANSA_RASPOLOZIVO"
    r.Range(2).Value = "Nedovoljno OM avansa! Raspolo" & ChrW(382) & "ivo:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_GRESKA_PRI_CUVANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju OM ulaza. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_VALIDACIJA_NIJE_PROSLA"
    r.Range(2).Value = "Validacija nije pro" & ChrW(353) & "la. Proverite kg i ambala" & ChrW(382) & "u (razlika mora biti 0)."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_GRESKA_PRI_CUVANJU_3"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju zbirne. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_LBL_NEISPRAVNA_KOLICINA_AMBALAZE"
    r.Range(2).Value = "Neispravna koli" & ChrW(269) & "ina ambala" & ChrW(382) & "e"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_UNESITE_ISPRAVNU_KOLICINU_3"
    r.Range(2).Value = "Unesite ispravnu koli" & ChrW(269) & "inu vra" & ChrW(263) & "ene ambala" & ChrW(382) & "e!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_GRESKA_PRI_CUVANJU_4"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju prijemnice. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_UNESITE_AMBALAZU_ILI_2"
    r.Range(2).Value = "Unesite ambala" & ChrW(382) & "u ili uplatu kupca."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_MSG_GRESKA_PRI_CUVANJU_5"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju izlaza kupca. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_ERR_GRESKA_PRI_PRIKAZU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri prikazu storniranih:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_LBL_STAMPAJ"
    r.Range(2).Value = ChrW(352) & "tampaj"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_ERR_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju fakturisanja:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_ERR_GRESKA_PRI_UCITAVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju prijemnica:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_MSG_ISTA_PRIJEMNICA_IZABRANA"
    r.Range(2).Value = "Ista prijemnica je izabrana vi" & ChrW(353) & "e puta:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_MSG_IZABRANA_PRIJEMNICA_STORNIRANA"
    r.Range(2).Value = "Izabrana prijemnica je stornirana i ne mo" & ChrW(382) & "e se fakturisati."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_MSG_IZABRANA_PRIJEMNICA_VEC"
    r.Range(2).Value = "Izabrana prijemnica je vec fakturisana i ne mo" & ChrW(382) & "e biti ukljucena u novu fakturu."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_MSG_GRESKA_PRI_KREIRANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri kreiranju fakture. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_ERR_GRESKA_PRI_IZRADI"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri izradi fakture:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_MSG_NIJE_PRONADEN_FAKTURE"
    r.Range(2).Value = "Nije pronaden ID fakture za " & ChrW(353) & "tampu."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_ERR_GRESKA_PRI_STAMPANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(353) & "tampanju:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_IZVESTAJI"
    r.Range(2).Value = "Izve" & ChrW(353) & "taji"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_PREGLED_SALDO_OTKUPLJENE"
    r.Range(2).Value = "Pregled saldo, otkupljene robe, ambala" & ChrW(382) & "e i prosecne cene"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_PRIKAZI"
    r.Range(2).Value = "Prika" & ChrW(382) & "i"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_STAMPAJ_KARTICU"
    r.Range(2).Value = ChrW(352) & "tampaj karticu"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_TIP_IZVESTAJA"
    r.Range(2).Value = "TIP IZVE" & ChrW(352) & "TAJA"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_AGRO_ZADUZENJE"
    r.Range(2).Value = "Agro zadu" & ChrW(382) & "enje"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_AMBALAZA"
    r.Range(2).Value = "Ambala" & ChrW(382) & "a"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_KES_OTKUPAC"
    r.Range(2).Value = "Ke" & ChrW(353) & " otkupac"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_ZADUZENJE"
    r.Range(2).Value = "Zadu" & ChrW(382) & "enje"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "RPT_LBL_RAZDUZENJE"
    r.Range(2).Value = "Razdu" & ChrW(382) & "enje"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "MATICNI_ERR_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju menija " & ChrW(353) & "ifarnika:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "MATICNI_ERR_GRESKA_PRI_OTVARANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju " & ChrW(353) & "ifarnika:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_POKUSAJ_PONOVO"
    r.Range(2).Value = ". Poku" & ChrW(353) & "aj ponovo."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_UNESITE_ISPRAVNU_KOLICINU"
    r.Range(2).Value = "Unesite ispravnu koli" & ChrW(269) & "inu izdate ambala" & ChrW(382) & "e!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_IZABERITE_TIP_AMBALAZE"
    r.Range(2).Value = "Izaberite tip ambala" & ChrW(382) & "e (za II klasu)!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_IZABERITE_TIP_AMBALAZE_2"
    r.Range(2).Value = "Izaberite tip ambala" & ChrW(382) & "e (za izdatu ambala" & ChrW(382) & "u)!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_BRUTO_REZIM_UNESITE"
    r.Range(2).Value = "Bruto re" & ChrW(382) & "im: unesite broj gajbi za I klasu"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_BRUTO_REZIM_UNESITE_2"
    r.Range(2).Value = "Bruto re" & ChrW(382) & "im: unesite broj gajbi za II klasu"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_ZELITE_IPAK_NASTAVITE"
    r.Range(2).Value = ChrW(381) & "elite li ipak da nastavite?"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_GRESKA_PRI_CUVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju otkupa. Promene su vra" & ChrW(263) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_ERR_GRESKA_PRI_UNOSU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri unosu otkupa:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_ERR_GRESKA_PRI_POKRETANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri pokretanju glavnog ekrana:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_GRESKA_PRI_PROVERI"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri proveri dokumenata. Pogledajte log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_IZVESTAJ"
    r.Range(2).Value = "Izve" & ChrW(353) & "taj"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_MARZA"
    r.Range(2).Value = "Mar" & ChrW(382) & "a"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_IZVESTAJ_SLEDLJIVOSTI"
    r.Range(2).Value = "Izve" & ChrW(353) & "taj o sledljivosti"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_GRESKA_PRI_UVOZU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri uvozu banke. Otvaram mapiranje za postojece stavke."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_MSG_GRESKA_PRI_UVOZU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri uvozu bankovnih izvoda:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_SEKCIJA_IZVESTAJ_SLEDLJIVOSTI"
    r.Range(2).Value = "Sekcija: Izve" & ChrW(353) & "taj o sledljivosti"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_GRESKA_PRI_SNIMANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri snimanju. Pogledajte log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_ERR_GRESKA_PRI_SNIMANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri snimanju:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_ERR_FAJL_NIJE_USPESNO"
    r.Range(2).Value = "Fajl nije uspe" & ChrW(353) & "no sa" & ChrW(269) & "uvan ili aplikacija nije zatvorena:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_ERR_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju mati" & ChrW(269) & "nih podataka:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju sekcije:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_ERR_GRESKA_PRI_OTVARANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju sekcije '"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_DANASNJI_OTKUP"
    r.Range(2).Value = "Dana" & ChrW(353) & "nji otkup"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_OTPREMNICA"
    r.Range(2).Value = "otpremnica  " & ChrW(8226)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "PAL_LBL_PREGLED_PALETA_STAMPA"
    r.Range(2).Value = "Pregled paleta, " & ChrW(353) & "tampa i prerada"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_LBL_POSALJI_SEF"
    r.Range(2).Value = "Po" & ChrW(353) & "alji na SEF"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_LBL_OSVEZI_STATUS"
    r.Range(2).Value = "Osve" & ChrW(382) & "i status"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_LBL_OTKAZI_SLANJE_SEF"
    r.Range(2).Value = "Otka" & ChrW(382) & "i slanje na SEF"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_LBL_OSVEZI_SVE_PENDING"
    r.Range(2).Value = "Osve" & ChrW(382) & "i sve Pending"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_ERR_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju SEF forme:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_SEF_STATUS_OSVEZEN"
    r.Range(2).Value = "SEF status osve" & ChrW(382) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_CANCEL_USPESNO_POSLAT"
    r.Range(2).Value = "Cancel uspe" & ChrW(353) & "no poslat."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_STORNO_USPESNO_POSLAT"
    r.Range(2).Value = "Storno uspe" & ChrW(353) & "no poslat."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_RECOVERY_ZAVRSEN"
    r.Range(2).Value = "Recovery zavr" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_PENDING_FAKTURE_OSVEZENE"
    r.Range(2).Value = "Pending fakture osve" & ChrW(382) & "ene."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_SEF_SENDING_RECOVERY"
    r.Range(2).Value = "SEF_SENDING recovery zavr" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SLED_LBL_POVEZI"
    r.Range(2).Value = "Pove" & ChrW(382) & "i"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_LBL_OBRISI_GEO"
    r.Range(2).Value = "Obri" & ChrW(353) & "i geo"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_LBL_CENE_PROIZVODU_SVAKA"
    r.Range(2).Value = "Cene po proizvodu " & ChrW(8212) & " svaka promena je novi red (vazi poslednji)"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_ERR_GRESKA_PRI_PROMENI"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri promeni statusa:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_ERR_GRESKA_PRI_UCITAVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju liste:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_UNESITE_KATASTARSKU_OPSTINU"
    r.Range(2).Value = "Unesite katastarsku op" & ChrW(353) & "tinu!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_UNESITE_VALIDNU_POVRSINU"
    r.Range(2).Value = "Unesite validnu povr" & ChrW(353) & "inu!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_DODAVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri dodavanju!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_DODAVANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri dodavanju cene!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_ERR_GRESKA_PRI_DODAVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri dodavanju:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_NOVU_CENU_KORISTITE"
    r.Range(2).Value = "Za novu cenu koristite 'Dodaj' " & ChrW(8212) & " stari redovi ostaju radi istorije."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_ERR_GRESKA_PRI_IZMENI"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri izmeni:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_ERR_GRESKA_PRI_UCITAVANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju stanica:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "AGRO_MSG_GRESKA_PRI_UNOSU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri unosu magacina, promene vra" & ChrW(263) & "ene:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "BANKA_LBL_PDF_AUSWAHLEN"
    r.Range(2).Value = "Izaberi PDF"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "GAUTH_MSG_TOKEN_AUSTAUSCH_FEHLGESCHLAGEN"
    r.Range(2).Value = "Razmena tokena nije uspela. Proveri Client ID/Secret."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_UVOZ_OTK_NIJE"
    r.Range(2).Value = "Uvoz OTK nije potvr" & ChrW(273) & "en zbog fatal sync gre" & ChrW(353) & "ke."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_GRESKE"
    r.Range(2).Value = "Gre" & ChrW(353) & "ke:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_UVOZ_OTK_ZAVRSEN"
    r.Range(2).Value = "Uvoz OTK zavr" & ChrW(353) & "en sa gre" & ChrW(353) & "kama."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_UVOZ_OTK_ZAVRSEN_2"
    r.Range(2).Value = "Uvoz OTK zavr" & ChrW(353) & "en!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_GRESKA_PRI_UVOZU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri uvozu OTK:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_PWA_UVOZ_NIJE"
    r.Range(2).Value = "PWA uvoz nije potvr" & ChrW(273) & "en. Promene su vra" & ChrW(263) & "ene zbog fatal sync gre" & ChrW(353) & "ke. Proveri log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_PWA_UVOZ_ZAVRSEN"
    r.Range(2).Value = "PWA uvoz zavr" & ChrW(353) & "en i potvr" & ChrW(273) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_UVOZ_ZBIRNIH_NIJE"
    r.Range(2).Value = "Uvoz zbirnih nije potvr" & ChrW(273) & "en zbog fatal sync gre" & ChrW(353) & "ke."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_UVOZ_ZBIRNIH_ZAVRSEN"
    r.Range(2).Value = "Uvoz zbirnih zavr" & ChrW(353) & "en sa gre" & ChrW(353) & "kama."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_ERR_UVOZ_ZBIRNIH_ZAVRSEN_2"
    r.Range(2).Value = "Uvoz zbirnih zavr" & ChrW(353) & "en!"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_GRESKA_PRI_UVOZU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri uvozu zbirnih:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_UVOZ_ZBIRNIH_ZAVRSEN"
    r.Range(2).Value = "Uvoz zbirnih zavr" & ChrW(353) & "en sa gre" & ChrW(353) & "kama ili fatal sync problemom."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_USPESNI_REDOVI_KOJI"
    r.Range(2).Value = "Uspe" & ChrW(353) & "ni redovi koji su potvr" & ChrW(273) & "eni kroz row-level TX ostaju upisani."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_NEUSPESNI_REDOVI_OZNACENI"
    r.Range(2).Value = "Neuspe" & ChrW(353) & "ni redovi su ozna" & ChrW(269) & "eni kao gre" & ChrW(353) & "ka gde je writeback uspeo."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SYNC_MSG_UVOZ_ZBIRNIH_ZAVRSEN_2"
    r.Range(2).Value = "Uvoz zbirnih zavr" & ChrW(353) & "en i potvr" & ChrW(273) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_OTKUPNI_BLOKOVI"
    r.Range(2).Value = "Otkupni blokovi  " & ChrW(187)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_SAKRIJ_BLOKOVE"
    r.Range(2).Value = ChrW(171) & "  Sakrij blokove"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_UKUPNO"
    r.Range(2).Value = "Ukupno kg: " & ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_BLOKOVIMA"
    r.Range(2).Value = "U blokovima: " & ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_OSTATAK"
    r.Range(2).Value = "Ostatak: " & ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_UKUPNO_AMB"
    r.Range(2).Value = "Ukupno amb: " & ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_BLOKOVIMA_AMB"
    r.Range(2).Value = "U blokovima amb: " & ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "OTKUP_LBL_OSTATAK_AMB"
    r.Range(2).Value = "Ostatak amb: " & ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_LBL_PODESAVANJA_TBLSEFCONFIG"
    r.Range(2).Value = "Pode" & ChrW(353) & "avanja (tblSEFConfig)"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_LBL_STR"
    r.Range(2).Value = ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_LBL_STR_2"
    r.Range(2).Value = ChrW(8212)
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_ERR_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju pode" & ChrW(353) & "avanja:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_PRESKOCENO_GRESKA"
    r.Range(2).Value = "Preskoceno (gre" & ChrW(353) & "ka):"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_ERR_GRESKA_PRI_CUVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_IZLAZ_NUZDI_ALT"
    r.Range(2).Value = "(Izlaz u nu" & ChrW(382) & "di: Alt+F8 -> ShowConfigSheet.)"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_SETUP_USPESNO_ZAVRSEN"
    r.Range(2).Value = "Setup je uspe" & ChrW(353) & "no zavr" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_PODESAVANJA_MATICNI_PODACI"
    r.Range(2).Value = "Pode" & ChrW(353) & "avanja: Mati" & ChrW(269) & "ni podaci -> Pode" & ChrW(353) & "avanja (tblSEFConfig je skriven)."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_SETUP_ZAVRSEN_ALI"
    r.Range(2).Value = "Setup je zavr" & ChrW(353) & "en, ali postoje stavke za proveru:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_ERR_GRESKA_TOKOM_SETUP"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka tokom setup-a:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_HEALTH_CHECK_PROSAO"
    r.Range(2).Value = "Health-check je pro" & ChrW(353) & "ao. Racunar je pode" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_HEALTH_CHECK_NASAO"
    r.Range(2).Value = "Health-check je na" & ChrW(353) & "ao stavke za proveru:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_ERR_GRESKA_TOKOM_HEALTH"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka tokom health-check-a:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_APLIKACIJA_RADI_LOKALNO"
    r.Range(2).Value = "Aplikacija radi lokalno " & ChrW(8212) & " Google/PWA se ne koristi niti proverava."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_BANKARSKI_FOLDERI_PODESENI"
    r.Range(2).Value = "Bankarski folderi su pode" & ChrW(353) & "eni."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_ERR_GRESKA_PRI_PODESAVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri pode" & ChrW(353) & "avanju bankarskih foldera:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_ERR_GRESKA_PRI_EXPORTU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri exportu parcela:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "DOK_ERR_NEMA_AMBALAZE_NOVCA"
    r.Range(2).Value = "Nema ambala" & ChrW(382) & "e ni novca za " & ChrW(269) & "uvanje."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_SENDING_FAKTURA_TRENUTNO"
    r.Range(2).Value = "- SENDING: Faktura se trenutno " & ChrW(353) & "alje."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_SENT_FAKTURA_USPESNO"
    r.Range(2).Value = "- SENT: Faktura uspe" & ChrW(353) & "no primljena na SEF."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_REJECTED_GRESKA_PROVERI"
    r.Range(2).Value = "- REJECTED: Gre" & ChrW(353) & "ka! Proveri 'Poslednja gre" & ChrW(353) & "ka'."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_IZABERI_FAKTURU_LISTE"
    r.Range(2).Value = "Izaberi fakturu iz liste -> Klikni 'Po" & ChrW(353) & "alji na SEF'."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_TEHNICKA_PODRSKA"
    r.Range(2).Value = "3. TEHNICKA PODR" & ChrW(352) & "KA:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_SVE_PROBLEME_KOJI"
    r.Range(2).Value = "Za sve probleme koji se ne re" & ChrW(353) & "avaju sa 'Osve" & ChrW(382) & "i status',"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SEF_MSG_KONTAKTIRAJ_ADMINISTRATORA_POSALJI"
    r.Range(2).Value = "kontaktiraj administratora i po" & ChrW(353) & "alji SEF Event Log (donja tabela)."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_PARCELA_NEMA_KATASTARSKI"
    r.Range(2).Value = "Parcela nema katastarski broj ili katastarsku op" & ChrW(353) & "tinu."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_OTVARANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju GeoSrbije. Pogledaj log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_CUVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri " & ChrW(269) & "uvanju geo podataka. Pogledaj log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_KLIKNI_JOS_JEDNOM"
    r.Range(2).Value = "Klikni jo" & ChrW(353) & " jednom za brisanje geo podataka."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_BRISANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri brisanju geo podataka. Pogledaj log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_UCITAVANJU"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri u" & ChrW(269) & "itavanju koordinata. Pogledaj log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_OTVARANJU_2"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju Google Maps. Pogledaj log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "STM_MSG_GRESKA_PRI_OTVARANJU_3"
    r.Range(2).Value = "Gre" & ChrW(353) & "ka pri otvaranju polygon editora. Pogledaj log."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "FAK_ERR_STORNIRANA_FAKTURA_MOZE"
    r.Range(2).Value = "Stornirana faktura se ne mo" & ChrW(382) & "e " & ChrW(353) & "tampati kao aktivna faktura:"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "LIC_MSG_SERVER_NEDOSTUPAN_OFFLINE"
    r.Range(2).Value = "Server nedostupan " & ChrW(8212) & " offline grace (masina je vezana)."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "LIC_MSG_PROPUSTAM_VEZANU_MASINU"
    r.Range(2).Value = "' " & ChrW(8212) & " propustam vezanu masinu."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "MATICNI_MSG_PODESAVANJA"
    r.Range(2).Value = "Pode" & ChrW(353) & "avanja"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "MONITO_ERR_NAMERNO_TESTIRANA_VBA"
    r.Range(2).Value = "Namerno testirana VBA gre" & ChrW(353) & "ka bez sensitive podataka"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_STAMPA_OTKUPNOG_LISTA"
    r.Range(2).Value = ChrW(352) & "tampa otkupnog lista"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_STAMPA_PALETNOG_LISTA"
    r.Range(2).Value = ChrW(352) & "tampa paletnog lista"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_STAMPA_PRIJEMNICE_AUTO"
    r.Range(2).Value = ChrW(352) & "tampa prijemnice (auto na unos)"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_KUPAC_UNOSI_BRUTO"
    r.Range(2).Value = "Kupac unosi BRUTO te" & ChrW(382) & "inu (oduzmi ambala" & ChrW(382) & "u)"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_MALINA_REZIM"
    r.Range(2).Value = "Malina re" & ChrW(382) & "im"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_PODESAVANJA_ZATVORENA"
    r.Range(2).Value = "Pode" & ChrW(353) & "avanja zatvorena."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "CFG_MSG_PRIKAZI_CONFIG_TABELU"
    r.Range(2).Value = "Prika" & ChrW(382) & "i config tabelu"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_OVAJ_RACUNAR_PROSAO"
    r.Range(2).Value = "Da li je ovaj racunar pro" & ChrW(353) & "ao SetupNewPC"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_DATUM_VREME_ZAVRSETKA"
    r.Range(2).Value = "Datum i vreme zavr" & ChrW(353) & "etka setup-a"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_FOLDER_BANKARSKE_IZVODE"
    r.Range(2).Value = "Folder za bankarske izvode sa gre" & ChrW(353) & "kom"
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_SEF_BASE_URL"
    r.Range(2).Value = "- SEF_BASE_URL nije pode" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_SEF_API_KEY"
    r.Range(2).Value = "- SEF_API_KEY nije pode" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_SEF_ENV_NIJE"
    r.Range(2).Value = "- SEF_ENV nije pode" & ChrW(353) & "en."
    Set r = lo.ListRows.Add
    r.Range(1).Value = "SETUP_MSG_NIJE_PODESEN"
    r.Range(2).Value = "nije pode" & ChrW(353) & "en:"
End Sub
